export default function TermsPage(){
  return <main className="legal-page"><article><a href="/">← Voltar</a><p className="eyebrow">DOCUMENTO PÚBLICO · VERSÃO TÉCNICA 2026-08-24</p><h1>Termos de Uso</h1><p>O Conte os Feitos é uma plataforma de jogos e desafios bíblicos. Estes termos permanecem sujeitos à revisão humana e jurídica antes da abertura pública ou Google Play.</p>
  <h2>1. Serviços</h2><p>A plataforma inclui sete jogos, Modo Livre, Desafios Diários, Eventos, perfil, XP, moedas virtuais, inventário, equipamentos, missões, conquistas e notificações. Recursos podem mudar ou ficar temporariamente indisponíveis.</p>
  <h2>2. Elegibilidade, maioridade e conta</h2><p>O serviço é destinado exclusivamente a pessoas com 18 anos ou mais. Ao criar uma conta, o usuário declara possuir pelo menos 18 anos, fornecer informações verdadeiras e manter uma conta pessoal. O usuário deve proteger suas credenciais e não compartilhar o acesso.</p>
  <h2>3. Segurança</h2><p>A administração pode suspender acesso por fraude, abuso, exploração de falhas ou risco à comunidade. O usuário deve comunicar suspeitas de comprometimento da conta.</p>
  <h2>4. Jogos e economia virtual</h2><p>Não é permitido automatizar respostas ou manipular resultados. XP, moedas e itens são recursos exclusivamente virtuais da plataforma, sem promessa de valor monetário, pagamento ou conversão.</p>
  <h2>5. Conteúdo e convivência</h2><p>Participantes e editores devem agir com respeito e não publicar conteúdo ilegal, ofensivo ou que exponha terceiros. Conteúdo produzido no CMS integra o acervo da organização.</p>
  <h2>6. Dados, exportação e exclusão</h2><p>O titular pode exportar dados e solicitar exclusão ou anonimização. O atendimento pode preservar registros mínimos necessários à integridade, segurança e exercício de direitos, bem como conteúdo organizacional, conforme a Política de Privacidade. Consulte as <a href="/privacidade/conta">instruções públicas de exclusão da conta</a>.</p>
  <h2>7. Responsável e contato</h2><p>O Conte os Feitos é atualmente mantido pela pessoa física responsável pelo projeto. Dúvidas sobre conta, suporte, documentos jurídicos ou privacidade podem ser enviadas para <a href="mailto:suporteconteosfeitos@gmail.com">suporteconteosfeitos@gmail.com</a>. CPF e endereço residencial não são publicados; a necessidade de endereço físico permanece sujeita à revisão jurídica.</p>
  <h2>8. Revisão necessária</h2><p><strong>REVISÃO HUMANA/JURÍDICA NECESSÁRIA ANTES DA ABERTURA PÚBLICA/GOOGLE PLAY.</strong></p><footer><a href="/privacidade">Ler Política de Privacidade</a></footer></article></main>;
}
