"use client";
import { useEffect, useMemo, useState } from "react";
export default function Members(){
 const [users,setUsers]=useState<any[]>([]),[target,setTarget]=useState<any>(null),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[temporaryPassword,setTemporaryPassword]=useState("");
 async function load(){const r=await fetch("/api/admin/users");if(r.status===401||r.status===403){location.href="/";return}setUsers(((await r.json()).users||[]).filter((u:any)=>u.role!=="admin"))} useEffect(()=>{load()},[]);
 const visible=useMemo(()=>users.filter(u=>(status==="all"||u.status===status)&&`${u.displayName} ${u.username}`.toLowerCase().includes(search.toLowerCase())),[users,search,status]);
 async function update(userId:string,change:any){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,...change})});setMessage(r.ok?"Cadastro atualizado.":"Não foi possível atualizar o cadastro.");if(r.ok)load()}
 async function resetPassword(user:any){if(!confirm(`Gerar uma senha temporária para ${user.displayName}? A conta será desconectada dos outros aparelhos.`))return;const r=await fetch(`/api/admin/users/${user.id}/reset-password`,{method:"POST"});const d=await r.json();if(r.ok){setTemporaryPassword(d.temporaryPassword);setMessage(`Senha temporária criada para ${user.displayName}. Copie e envie de forma privada.`)}else setMessage("Não foi possível redefinir a senha.")}
 async function remove(){const r=await fetch(`/api/admin/users/${target.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(r.ok){setTarget(null);setPassword("");setMessage("Participante removido e dados pessoais anonimizados.");load()}else setMessage(d.error==="invalid_password"?"Senha administrativa incorreta.":"Não foi possível remover.")}
 return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">PARTICIPANTES</p><h1>Gerenciar <em>membros</em></h1><p>Pesquise, suspenda, reative ou atribua a função de líder.</p></section>{message&&<p className="auth-message">{message}</p>}{temporaryPassword&&<aside className="temporary-password"><span><b>Senha temporária</b><code>{temporaryPassword}</code></span><button onClick={()=>navigator.clipboard.writeText(temporaryPassword)}>COPIAR</button><button onClick={()=>setTemporaryPassword("")}>FECHAR</button></aside>}<section className="member-tools"><input placeholder="Pesquisar por nome ou usuário" value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas as situações</option><option value="active">Ativos</option><option value="pending">Pendentes</option><option value="suspended">Suspensos</option><option value="rejected">Recusados</option></select></section><section className="admin-panel member-management">{visible.map(u=><article key={u.id}><div><strong>{u.displayName}</strong><small>@{u.username} · {u.status} · {u.role==="leader"?"líder":"participante"}</small></div><a href={`/perfil/publico?id=${u.id}`}>Perfil</a><button className="password" onClick={()=>resetPassword(u)}>Nova senha</button>{u.status!=="active"?<button className="safe" onClick={()=>update(u.id,{status:"active"})}>Reativar</button>:<button onClick={()=>update(u.id,{status:"suspended"})}>Suspender</button>}<button className="role" onClick={()=>update(u.id,{role:u.role==="leader"?"participant":"leader"})}>{u.role==="leader"?"Remover liderança":"Tornar líder"}</button><button onClick={()=>{setTarget(u);setMessage("")}}>Remover</button></article>)}{!visible.length&&<p className="empty">Nenhum membro encontrado.</p>}</section>{target&&<div className="modal-layer"><section className="admin-panel removal-modal"><h2>Remover {target.displayName}?</h2><p>A conta perderá acesso e os dados pessoais serão anonimizados.</p><label>Confirme sua senha administrativa<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label><div><button onClick={()=>setTarget(null)}>Cancelar</button><button className="danger" onClick={remove} disabled={!password}>REMOVER E ANONIMIZAR</button></div></section></div>}</main>;
}
