"use client";

import { useEffect, useMemo, useState } from "react";
import PlatformUserDetails from "./PlatformUserDetails";

export default function Members() {
  const [users, setUsers] = useState<any[]>([]), [target, setTarget] = useState<any>(null), [platformUser, setPlatformUser] = useState<any>(null);
  const [password, setPassword] = useState(""), [message, setMessage] = useState(""), [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [temporary, setTemporary] = useState("");
  const [selected, setSelected] = useState<string[]>([]), [batchStatus, setBatchStatus] = useState("suspended"), [batchPreview, setBatchPreview] = useState<any>(null), [lastOp, setLastOp] = useState("");
  async function load() { const response = await fetch("/api/admin/users"); if ([401, 403].includes(response.status)) { location.href = "/"; return; } setUsers(((await response.json()).users || []).filter((user: any) => user.role !== "admin")); setSelected([]); }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => users.filter(user => (status === "all" || user.status === status) && `${user.displayName} ${user.username}`.toLowerCase().includes(search.toLowerCase())), [users, search, status]);
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); }
  async function update(userId: string, change: any) { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, ...change }) }); setMessage(response.ok ? "Cadastro atualizado." : "Não foi possível atualizar."); if (response.ok) load(); }
  async function resetPassword(user: any) { if (!confirm(`Gerar senha temporária para ${user.displayName}?`)) return; const response = await fetch(`/api/admin/users/${user.id}/reset-password`, { method: "POST" }), result = await response.json(); if (response.ok) { setTemporary(result.temporaryPassword); setMessage(`Senha temporária criada para ${user.displayName}.`); } }
  async function remove() { const response = await fetch(`/api/admin/users/${target.id}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }), result = await response.json(); if (response.ok) { setTarget(null); setPassword(""); setMessage("Participante removido e anonimizado."); load(); } else setMessage(result.error === "invalid_password" ? "Senha incorreta." : "Não foi possível remover."); }
  async function previewBatch() { const response = await fetch("/api/admin/users/batch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: selected, status: batchStatus, password, preview: true }) }), result = await response.json(); if (response.ok) setBatchPreview(result.preview); else setMessage(result.error === "invalid_password" ? "Informe corretamente a senha administrativa." : "Seleção inválida."); }
  async function applyBatch() { const response = await fetch("/api/admin/users/batch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: selected, status: batchStatus, password }) }), result = await response.json(); if (response.ok) { setLastOp(result.operationId); setBatchPreview(null); setPassword(""); setMessage(`${result.count} membro(s) atualizado(s).`); load(); } }
  async function undo() { const response = await fetch("/api/admin/users/batch", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ operationId: lastOp }) }); if (response.ok) { setLastOp(""); setMessage("Operação desfeita."); load(); } }

  return <main className="admin-shell">
    <section className="admin-title"><p className="eyebrow">PARTICIPANTES</p><h1>Gerenciar <em>membros</em></h1><p>Pesquise, suspenda, reative ou atribua a função de líder.</p></section>
    {message && <p className="auth-message">{message}{lastOp && <button className="inline-undo" onClick={undo}>DESFAZER</button>}</p>}
    {temporary && <aside className="temporary-password"><span><b>Senha temporária</b><code>{temporary}</code></span><button onClick={() => navigator.clipboard.writeText(temporary)}>COPIAR</button><button onClick={() => setTemporary("")}>FECHAR</button></aside>}
    <section className="member-tools" aria-label="Filtros de membros"><label>Pesquisar membros<input aria-label="Pesquisar membros por nome ou usuário" placeholder="Nome ou usuário" value={search} onChange={event => setSearch(event.target.value)} /></label><label>Situação<select aria-label="Filtrar membros por situação" value={status} onChange={event => setStatus(event.target.value)}><option value="all">Todas as situações</option><option value="active">Ativos</option><option value="pending">Pendentes</option><option value="suspended">Suspensos</option><option value="rejected">Recusados</option></select></label></section>
    {visible.length > 0 && <aside className="batch-toolbar member-batch"><label><input type="checkbox" checked={selected.length === visible.length} onChange={event => setSelected(event.target.checked ? visible.map(user => user.id) : [])} /> Selecionar visíveis</label><strong>{selected.length} selecionado(s)</strong>{selected.length > 0 && <><select aria-label="Ação em lote" value={batchStatus} onChange={event => setBatchStatus(event.target.value)}><option value="suspended">Suspender</option><option value="active">Reativar</option></select>{batchStatus === "suspended" && <input aria-label="Senha administrativa para confirmar suspensão" type="password" placeholder="Senha administrativa" value={password} onChange={event => setPassword(event.target.value)} />}<button onClick={previewBatch}>REVISAR</button></>}</aside>}
    <section className="admin-panel member-management">{visible.map(user => <article className={selected.includes(user.id) ? "selected" : ""} key={user.id}><input type="checkbox" checked={selected.includes(user.id)} onChange={() => toggle(user.id)} aria-label={`Selecionar ${user.displayName}`} /><div><strong>{user.displayName}</strong><small>@{user.username} · {user.status} · {user.role === "leader" ? "líder" : "participante"}</small></div><button type="button" aria-label={`Ver dados da plataforma de ${user.displayName}`} onClick={() => setPlatformUser(user)}>Ver dados</button><button className="password" aria-label={`Gerar nova senha para ${user.displayName}`} onClick={() => resetPassword(user)}>Nova senha</button>{user.status !== "active" ? <button className="safe" aria-label={`Reativar ${user.displayName}`} onClick={() => update(user.id, { status: "active" })}>Reativar</button> : <button aria-label={`Suspender ${user.displayName}`} onClick={() => update(user.id, { status: "suspended" })}>Suspender</button>}<button className="role" aria-label={`${user.role === "leader" ? "Remover liderança de" : "Tornar líder"} ${user.displayName}`} onClick={() => update(user.id, { role: user.role === "leader" ? "participant" : "leader" })}>{user.role === "leader" ? "Remover liderança" : "Tornar líder"}</button><button aria-label={`Remover ${user.displayName}`} onClick={() => { setTarget(user); setMessage(""); }}>Remover</button></article>)}</section>
    {platformUser && <PlatformUserDetails userId={platformUser.id} userName={platformUser.displayName} onClose={() => setPlatformUser(null)} />}
    {target && <div className="modal-layer"><section className="admin-panel removal-modal"><h2>Remover {target.displayName}?</h2><p>A conta perderá acesso e os dados pessoais serão anonimizados.</p><label>Confirme sua senha<input type="password" value={password} onChange={event => setPassword(event.target.value)} /></label><div><button onClick={() => setTarget(null)}>Cancelar</button><button className="danger" onClick={remove}>REMOVER</button></div></section></div>}
    {batchPreview && <div className="modal-layer"><section className="admin-panel batch-preview"><h2>Confirmar alteração</h2><p>{batchPreview.count} membro(s) serão {batchPreview.status === "suspended" ? "suspensos" : "reativados"}.</p><ul>{batchPreview.members.map((user: any) => <li key={user.id}>{user.displayName}</li>)}</ul><footer><button onClick={() => setBatchPreview(null)}>Cancelar</button><button className="primary" onClick={applyBatch}>CONFIRMAR</button></footer></section></div>}
  </main>;
}
