"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

const GAME_NAMES: Record<string, string> = {"quiz-biblico":"Quiz","wordle-biblico":"Wordle","linha-do-tempo-biblica":"Linha do Tempo","memoria-biblica":"Memória","associacao-de-temas":"Associação","quem-sou-eu":"Quem Sou Eu","jogo-tres-pistas":"Três Pistas"};
const MODE_NAMES:Record<string,string>={FREE_PLAY:"Livre",DAILY:"Diário",EVENT:"Evento"};
const integer=(value:unknown)=>Number(value||0).toLocaleString("pt-BR");
const percent=(value:unknown)=>`${Number(value||0).toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;

export default function PlatformAnalyticsPage(){
 const[period,setPeriod]=useState("7d"),[data,setData]=useState<any>(null),[error,setError]=useState<{message:string;supportId?:string}|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/admin/platform-analytics?period=${period}`,{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw body;setData(body)}catch(problem:any){setError({message:problem?.message||"Não foi possível carregar os Analytics.",supportId:problem?.supportId})}finally{setLoading(false)}},[period]);
 useEffect(()=>{void load()},[load]);
 return <main className="admin-shell platform-analytics">
  <section className="admin-title"><p className="eyebrow">ANALYTICS DA PLATAFORMA</p><h1>Uso do <em>Conte os Feitos</em></h1><p>Indicadores agregados da organização, sem dados pessoais ou respostas individuais.</p></section>
  <div className="platform-analytics-period" role="group" aria-label="Período dos Analytics">{[["today","Hoje"],["7d","7 dias"],["30d","30 dias"]].map(([key,label])=><button key={key} type="button" className={period===key?"active":""} aria-pressed={period===key} onClick={()=>setPeriod(key)}>{label}</button>)}</div>
  {loading&&<section className="analytics-state" role="status" aria-live="polite"><span className="analytics-spinner" aria-hidden="true"/>Carregando indicadores…</section>}
  {!loading&&error&&<section className="analytics-state error" role="alert"><h2>Analytics indisponíveis</h2><p>{error.message}</p>{error.supportId&&<code>{error.supportId}</code>}<button type="button" onClick={()=>void load()}>Tentar novamente</button></section>}
  {!loading&&!error&&data&&<>
   <Section title="Visão geral" description="Cada indicador compara o período selecionado ao intervalo imediatamente anterior de mesma duração."><section className="platform-metric-grid" aria-label="Visão geral"><Metric label="Jogadores ativos" comparison={data.comparisons.activeUsers}/><Metric label="Partidas iniciadas" comparison={data.comparisons.started}/><Metric label="Concluídas" comparison={data.comparisons.completed} detail={percent(data.overview.completionRate)}/><Metric label="Daily aberto" comparison={data.comparisons.dailyOpened}/><Metric label="XP concedido" comparison={data.comparisons.xpGranted}/><Metric label="Saldo líquido de moedas" comparison={data.comparisons.netCoins}/></section></Section>
   <Section title="Tendências" description={`Séries diárias em UTC; o período “Hoje” respeita ${data.definitions.organizationTimeZone}.`}><Trend rows={data.trends}/></Section>
   <Section title="Engajamento por modo"><div className="analytics-mode-grid">{data.modes.map((item:any)=><article key={item.mode}><strong>{MODE_NAMES[item.mode]||item.mode}</strong><b>{integer(item.started)}</b><span>{integer(item.players)} jogadores · {integer(item.completed)} concluídas · {percent(item.completionRate)}</span></article>)}</div></Section>
   <Section title="Desafios Diários" description="DAILY_OPENED é emitido somente ao abrir a página de desafios; visualizações da Home não contam."><div className="analytics-funnel">{data.daily.funnel.stages.map((stage:any,index:number)=><article key={stage.name}><small>{["Abertura","Início","Marco 3/7","Marco 7/7"][index]}</small><strong>{integer(stage.users)}</strong>{stage.conversionFromPrevious!=null&&<span>{percent(stage.conversionFromPrevious)} da etapa anterior · {integer(stage.abandonmentFromPrevious)} abandonos</span>}</article>)}</div></Section>
   <Section title="Jogos"><div className="analytics-table-wrap"><table><thead><tr><th>Jogo</th><th>Iniciadas</th><th>Jogadores</th><th>Concluídas</th><th>Abandonos</th><th>Vitórias</th></tr></thead><tbody>{data.games.map((game:any)=><tr key={game.gameType}><th>{GAME_NAMES[game.gameType]||game.gameType}</th><td>{integer(game.started)}</td><td>{integer(game.players)}</td><td>{integer(game.completed)} <small>{percent(game.completionRate)}</small></td><td>{integer(game.abandoned)}</td><td>{integer(game.wins)} <small>{percent(game.winRate)}</small></td></tr>)}</tbody></table></div><p className="analytics-note">Scores brutos não são comparados entre jogos. Vitória e conclusão usam os resultados normalizados já persistidos.</p></Section>
   <Section title="Dificuldade editorial × observada" description={`Conclusão por exposição de conteúdo; mínimo de ${data.definitions.difficultyMinimumSample} participações por faixa.`}><div className="analytics-difficulty-grid">{data.games.flatMap((game:any)=>game.difficulties.map((item:any)=><article key={`${game.gameType}:${item.difficulty}`}><strong>{GAME_NAMES[game.gameType]} · {item.difficulty}</strong><span>{integer(item.sample)} participações</span>{item.sufficientSample?<b>{percent(item.completionRate)} concluídas</b>:<em>Amostra insuficiente</em>}</article>))}</div></Section>
   <Section title="Conteúdo" description="Baixo uso indica distribuição, não qualidade editorial."><div className="analytics-content-grid">{data.games.map((item:any)=><article key={item.gameType} className={item.exhaustionRisk?"risk":""}><strong>{GAME_NAMES[item.gameType]}</strong><span>{integer(item.published)} publicados · {integer(item.available)} disponíveis</span><span>{integer(item.usedContent)} usados · {integer(item.neverUsed)} nunca usados</span><span>Mais usado: {item.topContent[0]?`${integer(item.topContent[0].uses)} vezes`:"sem uso"}</span><span>Menor frequência: {item.leastUsedContent[0]?`${integer(item.leastUsedContent[0].uses)} vez(es)`:"sem uso"}</span>{item.exhaustionRisk&&<em>Risco de esgotamento</em>}</article>)}</div><Link className="analytics-context-link" href="/admin/conteudo/acervo">Abrir Acervo Universal</Link></Section>
   <div className="analytics-two-columns"><Section title="Retenção"><Comparison label="Usuários recorrentes" value={data.comparisons.returningUsers}/><Stat label="Novos usuários" value={data.retention.newUsers}/><Stat label="Taxa de retorno" value={percent(data.retention.returnRate)}/><Stat label="Sequência média" value={data.retention.averageStreak}/><p className="analytics-note">Recorrente: ativo no período e com atividade anterior ao início. Taxa: recorrentes ÷ novos + recorrentes.</p></Section><Section title="Economia"><Stat label="XP concedido" value={data.economy.xpGranted}/><Stat label="Moedas emitidas" value={data.economy.coinsGranted}/><Stat label="Moedas gastas" value={data.economy.coinsSpent}/><Stat label="Saldo líquido" value={data.economy.netCoins}/><Stat label="Compras" value={data.economy.purchases}/><Stat label="Usuários no teto FREE_PLAY" value={data.economy.freePlayCap.reachedUsers}/><p className="analytics-note">Teto FREE_PLAY: 15 moedas por usuário/dia. Moedas bloqueadas não são persistidas e não são inferidas.</p></Section></div>
   <Section title="Origens da economia"><div className="analytics-origin-grid">{data.economy.rewardOrigins.map((item:any)=><article key={`${item.asset}:${item.source}`}><strong>{item.source}</strong><span>{item.asset.toUpperCase()} · {integer(item.entries)} lançamentos</span><b>{integer(item.amount)}</b></article>)}</div></Section>
   <Section title="Eventos" description="O funil confiável termina em usuários com ao menos uma partida concluída; isso não equivale à conclusão integral do Evento."><div className="analytics-funnel">{data.events.funnel.stages.map((stage:any,index:number)=><article key={stage.name}><small>{["Participaram","Iniciaram","Progrediram"][index]}</small><strong>{integer(stage.users)}</strong>{stage.conversionFromPrevious!=null&&<span>{percent(stage.conversionFromPrevious)} da etapa anterior · {integer(stage.abandonmentFromPrevious)} abandonos</span>}</article>)}</div><div className="analytics-event-list">{data.events.items.map((item:any)=><article key={item.eventId}><strong>{item.title}</strong><span>{integer(item.participants)} participantes · {integer(item.sessions)} sessões · {integer(item.games)} jogos</span><span>{integer(item.completed)} partidas concluídas · {integer(item.xpRewarded)} XP · {integer(item.coinsRewarded)} moedas</span></article>)}{!data.events.items.length&&<p>Sem Eventos no período.</p>}</div><Unavailable text="Conclusão integral do Evento ainda não possui projeção própria confiável."/></Section>
  </>}
 </main>
}
function Metric({label,comparison,detail}:{label:string;comparison:any;detail?:string}){return <article><small>{label}</small><b>{integer(comparison.current)}</b><ComparisonText comparison={comparison}/>{detail&&<span>{detail}</span>}</article>}
function ComparisonText({comparison}:{comparison:any}){const sign=comparison.difference>0?"+":"";return <span>{sign}{integer(comparison.difference)} vs anterior{comparison.percentChange==null?" · base anterior zero":` · ${sign}${percent(comparison.percentChange)}`}</span>}
function Comparison({label,value}:{label:string;value:any}){return <div className="analytics-stat"><span>{label}</span><strong>{integer(value.current)}</strong><small><ComparisonText comparison={value}/></small></div>}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="admin-panel platform-analytics-section"><h2>{title}</h2>{description&&<p className="analytics-definition">{description}</p>}{children}</section>}
function Stat({label,value}:{label:string;value:unknown}){return <div className="analytics-stat"><span>{label}</span><strong>{typeof value==="string"?value:integer(value)}</strong></div>}
function Unavailable({text}:{text:string}){return <p className="analytics-unavailable"><b>Indisponível:</b> {text}</p>}
function Trend({rows}:{rows:any[]}){const max=Math.max(1,...rows.map(row=>Number(row.started||0)));return <div className="platform-trend" role="img" aria-label="Tendência diária de partidas iniciadas">{rows.map(row=><article key={row.day}><div><i style={{height:`${Math.max(4,Number(row.started||0)*100/max)}%`}}/></div><strong>{row.day.slice(5)}</strong><span>{integer(row.activeUsers)} ativos</span><span>{integer(row.started)} iniciadas</span><span>{integer(row.completed)} concluídas</span></article>)}{!rows.length&&<p>Sem atividade no período.</p>}</div>}
