"use client";
import { useCallback, useEffect, useState } from "react";

const GAME_NAMES: Record<string, string> = {"quiz-biblico":"Quiz","wordle-biblico":"Wordle","linha-do-tempo-biblica":"Linha do Tempo","memoria-biblica":"Memória","associacao-de-temas":"Associação","quem-sou-eu":"Quem Sou Eu","jogo-tres-pistas":"Três Pistas"};
const integer=(value:unknown)=>Number(value||0).toLocaleString("pt-BR");
const percent=(value:unknown)=>`${Number(value||0).toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;

export default function PlatformAnalyticsPage(){
 const[period,setPeriod]=useState("7d"),[data,setData]=useState<any>(null),[error,setError]=useState<{message:string;supportId?:string}|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/admin/platform-analytics?period=${period}`,{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw body;setData(body)}catch(problem:any){setError({message:problem?.message||"Não foi possível carregar os Analytics.",supportId:problem?.supportId})}finally{setLoading(false)}},[period]);
 useEffect(()=>{void load()},[load]);
 return <main className="admin-shell platform-analytics">
  <section className="admin-title"><p className="eyebrow">ANALYTICS DA PLATAFORMA</p><h1>Uso do <em>Conte os Feitos</em></h1><p>Indicadores agregados da organização, sem dados pessoais ou respostas individuais.</p></section>
  <div className="platform-analytics-period" role="group" aria-label="Período dos Analytics">{[["today","Hoje"],["7d","7 dias"],["30d","30 dias"]].map(([key,label])=><button key={key} type="button" className={period===key?"active":""} aria-pressed={period===key} onClick={()=>setPeriod(key)}>{label}</button>)}</div>
  {loading&&<section className="analytics-state" role="status" aria-live="polite"><span className="analytics-spinner" aria-hidden="true"/>Carregando indicadores…</section>}
  {!loading&&error&&<section className="analytics-state error" role="alert"><h2>Analytics indisponíveis</h2><p>{error.message}</p>{error.supportId&&<code>{error.supportId}</code>}<button type="button" onClick={()=>void load()}>Tentar novamente</button></section>}
  {!loading&&!error&&data&&<>
   <section className="platform-metric-grid" aria-label="Visão geral"><Metric label="Jogadores ativos" value={integer(data.overview.players)}/><Metric label="Partidas iniciadas" value={integer(data.overview.started)}/><Metric label="Concluídas" value={integer(data.overview.completed)} detail={percent(data.overview.completionRate)}/><Metric label="Abandonadas" value={integer(data.overview.abandoned)}/><Metric label="Vitórias" value={integer(data.overview.wins)} detail={percent(data.overview.winRate)}/><Metric label="Derrotas" value={integer(data.overview.losses)}/></section>
   <Section title="Modos"><div className="analytics-mode-grid">{data.modes.map((item:any)=><article key={item.mode}><strong>{item.mode.replace("_"," ")}</strong><b>{integer(item.started)}</b><span>{integer(item.completed)} concluídas · {percent(item.completionRate)}</span></article>)}</div></Section>
   <Section title="Jogos"><div className="analytics-table-wrap"><table><thead><tr><th>Jogo</th><th>Iniciadas</th><th>Jogadores</th><th>Concluídas</th><th>Abandonos</th><th>Vitórias</th></tr></thead><tbody>{data.games.map((game:any)=><tr key={game.gameType}><th>{GAME_NAMES[game.gameType]||game.gameType}</th><td>{integer(game.started)}</td><td>{integer(game.players)}</td><td>{integer(game.completed)} <small>{percent(game.completionRate)}</small></td><td>{integer(game.abandoned)}</td><td>{integer(game.wins)} <small>{percent(game.winRate)}</small></td></tr>)}</tbody></table></div></Section>
   <div className="analytics-two-columns"><Section title="Desafios Diários"><Stat label="Iniciadas" value={data.daily.started}/><Stat label="Concluídas" value={data.daily.completed}/><Stat label="Completaram 3" value={data.daily.completed3}/><Stat label="Completaram 7" value={data.daily.completed7}/><Unavailable text="Aberturas não são persistidas atualmente."/></Section><Section title="Eventos"><Stat label="Participantes" value={data.events.participants}/><Stat label="Jogos" value={data.events.games}/><Stat label="Concluídos" value={data.events.completed}/><Stat label="Vitórias" value={data.events.wins}/><Unavailable text="Conclusão integral do Evento ainda não possui projeção própria."/></Section></div>
   <Section title="Conteúdo"><div className="analytics-content-grid">{data.content.map((item:any)=><article key={item.gameType} className={item.exhaustionRisk?"risk":""}><strong>{GAME_NAMES[item.gameType]}</strong><span>{integer(item.published)} publicados</span><span>{integer(item.available)} disponíveis</span><span>{integer(item.usedContent)} usados no período</span><span>{integer(item.neverUsed)} nunca usados</span>{item.exhaustionRisk&&<em>Risco de esgotamento</em>}</article>)}</div></Section>
   <div className="analytics-two-columns"><Section title="Retenção"><Stat label="Novos usuários" value={data.retention.newUsers}/><Stat label="Usuários recorrentes" value={data.retention.returningUsers}/><Stat label="Sequência média" value={data.retention.averageStreak}/><p className="analytics-note">Mede usuários recorrentes e streak; não representa retenção formal D1/D7.</p></Section><Section title="Economia"><Stat label="XP concedido" value={data.economy.xpGranted}/><Stat label="Moedas concedidas" value={data.economy.coinsGranted}/><Stat label="Moedas gastas" value={data.economy.coinsSpent}/><Stat label="Compras" value={data.economy.purchases}/><Stat label="Saldo agregado" value={data.economy.aggregateBalance}/></Section></div>
  </>}
 </main>
}
function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <article><small>{label}</small><b>{value}</b>{detail&&<span>{detail}</span>}</article>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-panel platform-analytics-section"><h2>{title}</h2>{children}</section>}
function Stat({label,value}:{label:string;value:unknown}){return <div className="analytics-stat"><span>{label}</span><strong>{integer(value)}</strong></div>}
function Unavailable({text}:{text:string}){return <p className="analytics-unavailable"><b>Indisponível:</b> {text}</p>}
