"use client";
import { useEffect, useState } from "react";

const quarterLabel = (number: number) => `${number}º trimestre`;
const statusLabels: Record<string, string> = { draft: "Planejada", active: "Em andamento", closed: "Encerrada", cancelled: "Cancelada" };
export default function AdminSeasons() {
  const [items, setItems] = useState<any[]>([]), [year, setYear] = useState(new Date().getFullYear()), [quarter, setQuarter] = useState(Math.floor(new Date().getMonth() / 3) + 1), [title, setTitle] = useState(""), [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/seasons"); if (!response.ok) { location.href = "/admin"; return; } setItems((await response.json()).seasons || []); }
  useEffect(() => { load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/seasons", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ year, quarter, title: title || `${quarterLabel(quarter)} de ${year}` }) }), data = await response.json(); setMessage(response.ok ? "Temporada criada." : data.error === "season_exists" ? "Já existe uma temporada neste trimestre." : "Confira os dados."); if (response.ok) { setTitle(""); load(); } }
  return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">CICLOS TRIMESTRAIS</p><h1>Gerenciar <em>temporadas</em></h1><p>Planeje, acompanhe e congele a classificação final de cada trimestre.</p></section>{message && <p className="auth-message">{message}</p>}<form className="admin-panel season-form" onSubmit={create}><label>Ano<input type="number" min="2020" max="2100" value={year} onChange={event => setYear(Number(event.target.value))}/></label><label>Trimestre<select value={quarter} onChange={event => setQuarter(Number(event.target.value))}>{[1, 2, 3, 4].map(value => <option value={value} key={value}>{quarterLabel(value)}</option>)}</select></label><label>Nome opcional<input value={title} onChange={event => setTitle(event.target.value)} placeholder={`${quarterLabel(quarter)} de ${year}`}/></label><button className="primary">CRIAR TEMPORADA</button></form><section className="admin-panel season-list">{items.map(item => <article key={item.id}><div><small>{item.year} · {quarterLabel(item.quarter)}</small><h2>{item.title}</h2><p>{new Date(item.starts_at).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })} até {new Date(item.ends_at).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })} · {item.roundCount} rodada(s)</p></div><b>{statusLabels[item.status] || item.status}</b><footer><a href={`/admin/temporadas/detalhes?id=${item.id}`}>PAINEL E DETALHES</a></footer></article>)}</section></main>;
}
