"use client";
import { useCallback, useEffect, useState } from "react";
import { csvDocument } from "../../csv-export";
const pct=(value:any)=>`${Number(value||0)}%`;

export default function AnalyticsPage(){
 const[days,setDays]=useState(90),[data,setData]=useState<any>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");const response=await fetch(`/api/admin/analytics?days=${days}`,{cache:"no-store"});if(response.status===401||response.status===403){setError("Seu perfil não possui acesso aos relatórios.");return}if(!response.ok){setError("Não foi possível carregar as análises. Consulte o Diagnóstico do sistema.");return}setData(await response.json())},[days]);
 useEffect(()=>{void load()},[load]);
 function exportCsv(){if(!data)return;const rows=[
  ["Tipo","Item","Respostas/Tentativas","Precisão/Pontuação"],
  ...data.dimensions.map((item:any)=>["Tema/Livro",`${item.theme} · ${item.book} · ${item.difficulty}`,item.answers,item.accuracy]),
  ...data.hardest.map((item:any)=>["Pergunta",item.prompt,item.answers,item.accuracy]),
  ...data.participation.map((item:any)=>["Jornada",item.title,item.attempts,item.averageScore]),
 ],url=URL.createObjectURL(new Blob([csvDocument(rows)],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`analises-${days}-dias.csv`;a.click();URL.revokeObjectURL(url)}
 if(error)return <main className="admin-shell"><section className="admin-panel bank-empty"><h1>Análises indisponíveis</h1><p>{error}</p><a href="/admin/diagnostico">ABRIR DIAGNÓSTICO</a></section></main>;
 if(!data)return <main className="admin-shell"><p role="status">Carregando análises...</p></main>;
 const summary=data.summary||{};
 return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">INTELIGÊNCIA DA COMUNIDADE</p><h1>Painel <em>analítico</em></h1><p>Indicadores das tentativas oficiais nos últimos {days} dias.</p></section><section className="analytics-actions"><select aria-label="Período das análises" value={days} onChange={event=>setDays(Number(event.target.value))}><option value="30">30 dias</option><option value="90">90 dias</option><option value="180">180 dias</option><option value="365">1 ano</option></select><button onClick={exportCsv}>EXPORTAR CSV</button></section><section className="metric-grid"><article><small>Participantes</small><b>{summary.participants||0}</b></article><article><small>Tentativas</small><b>{summary.attempts||0}</b></article><article><small>Jornadas</small><b>{summary.rounds||0}</b></article><article><small>Pontuação média</small><b>{Number(summary.averageScore||0).toLocaleString("pt-BR")}</b></article><article><small>Precisão média</small><b>{pct(summary.averageAccuracy)}</b></article></section><div className="analytics-columns"><section className="admin-panel"><h2>Evolução semanal</h2><div className="trend-chart">{data.trend.map((item:any)=><div key={item.week}><span>{item.week}</span><i style={{height:`${Math.max(5,Number(item.averageCorrect||0)*9)}%`}}/><small>{item.averageCorrect} acertos</small></div>)}</div></section><section className="admin-panel"><h2>Desempenho por conteúdo</h2><div className="accuracy-list">{data.dimensions.slice(0,12).map((item:any,index:number)=><article key={index}><span><b>{item.theme}</b><small>{item.book} · {item.difficulty} · {item.answers} respostas</small></span><div><i style={{width:pct(item.accuracy)}}/><b>{pct(item.accuracy)}</b></div></article>)}</div></section></div><section className="admin-panel analytics-table"><h2>Perguntas que mais precisam de revisão</h2>{data.hardest.map((item:any,index:number)=><article key={item.id}><b>{index+1}</b><span><strong>{item.prompt}</strong><small>{item.reference} · {item.theme} · {item.answers} respostas · média de {(Number(item.averageTimeMs)/1000).toFixed(1)}s</small></span><em>{pct(item.accuracy)}</em></article>)}{!data.hardest.length&&<p>São necessárias pelo menos duas respostas por pergunta para esta análise.</p>}</section><section className="admin-panel analytics-table"><h2>Participação por Jornada</h2>{data.participation.map((item:any)=><article key={item.id}><span><strong>{item.title}</strong><small>{new Date(item.opensAt).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"})} · {item.roundType==="special"?"Evento especial":"Regular"}</small></span><em>{item.participants} participante(s) · {item.attempts} tentativa(s)</em></article>)}</section></main>
}
