"use client";
import { useEffect, useRef, useState } from "react";

type Choice={id:string;text:string}; type Question={id:string;reference?:string;prompt:string;choices:Choice[]};
type Attempt={id:string;attemptNumber:number;mode:string;secondsPerQuestion:number;questions:Question[]};

export default function PlayPage(){
 const [attempt,setAttempt]=useState<Attempt|null>(null);const [round,setRound]=useState<any>(null);const [index,setIndex]=useState(0);const [time,setTime]=useState(15);const [selected,setSelected]=useState<string|null>(null);const [feedback,setFeedback]=useState<any>(null);const [score,setScore]=useState(0);const [result,setResult]=useState<any>(null);const [error,setError]=useState("");const started=useRef(Date.now());
 useEffect(()=>{fetch('/api/rounds/current').then(async r=>{if(r.status===401){location.href='/';return;}const data=await r.json();setRound(data.round);});},[]);
 useEffect(()=>{if(!attempt||selected)return;if(time<=0){answer("");return;}const timer=setTimeout(()=>setTime(t=>t-1),1000);return()=>clearTimeout(timer);},[attempt,index,time,selected]);
 async function start(mode='official'){if(!round)return;setError('');const r=await fetch('/api/attempts/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({roundId:round.id,mode})});const data=await r.json();if(!r.ok){setError(data.error==='attempt_limit'?'Suas três tentativas oficiais foram utilizadas.': 'Não foi possível iniciar.');return;}setAttempt(data.attempt);setTime(data.attempt.secondsPerQuestion);started.current=Date.now();}
 async function answer(choiceId:string){if(!attempt||selected)return;setSelected(choiceId||'timeout');const question=attempt.questions[index];const elapsed=Math.min(Date.now()-started.current,attempt.secondsPerQuestion*1000);const r=await fetch(`/api/attempts/${attempt.id}/answer`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({questionId:question.id,choiceId:choiceId||question.choices[0].id,timedOut:!choiceId,questionOrder:index,choiceOrder:question.choices.map(c=>c.id),responseTimeMs:choiceId?elapsed:attempt.secondsPerQuestion*1000})});const data=await r.json();setFeedback({...data,chosen:choiceId});if(data.points)setScore(s=>s+data.points);}
 async function next(){if(!attempt)return;if(index<attempt.questions.length-1){setIndex(i=>i+1);setSelected(null);setFeedback(null);setTime(attempt.secondsPerQuestion);started.current=Date.now();return;}const r=await fetch(`/api/attempts/${attempt.id}/finish`,{method:'POST'});const data=await r.json();if(r.ok)setResult(data.result);else setError('Não foi possível concluir a tentativa.');}
 if(result)return <main className="shell result-screen"><header className="brand"><span className="brand-dot">✦</span> CONTE OS FEITOS</header><section className="result-card"><div className="trophy">🏆</div><p className="eyebrow">TENTATIVA CONCLUÍDA</p><h1>Você fez <em>{result.score.toLocaleString('pt-BR')}</em></h1><div className="score-block"><small>ACERTOS</small><strong>{result.correctAnswers}/10</strong><span>maior sequência: {result.maxStreak}</span></div><button className="primary" onClick={()=>location.href='/rankings'}>VER RANKINGS <span>→</span></button><button className="auth-switch" onClick={()=>location.href='/'}>Voltar ao início</button></section></main>;
 if(!attempt)return <main className="shell start-screen"><header className="brand"><span className="brand-dot">✦</span> CONTE OS FEITOS</header><section className="hero-card"><div className="orbit"><span>📖</span><i/><b/></div>{round?<><p className="eyebrow">RODADA DA SEMANA</p><h1>{round.title}</h1><p className="intro">{round.theme}<br/>{3-round.attemptsUsed} tentativa(s) oficial(is) disponível(is).</p><button className="primary" onClick={()=>start('official')} disabled={round.attemptsUsed>=3}>INICIAR TENTATIVA <span>→</span></button>{round.attemptsUsed>=3&&<button className="auth-switch" onClick={()=>start('practice')}>Jogar no modo treino</button>}</>:<><p className="eyebrow">AGUARDE</p><h1>Nenhuma rodada <em>ativa</em></h1><p className="intro">A próxima competição aparecerá aqui no horário programado.</p></>}{error&&<p className="auth-message">{error}</p>}</section></main>;
 const question=attempt.questions[index];
 return <main className="shell game-screen"><header className="game-header"><div className="brand"><span className="brand-dot">✦</span> CONTE OS FEITOS</div><div className="live-score"><small>PONTOS</small><b>{score.toLocaleString('pt-BR')}</b></div></header><div className="progress"><i style={{width:`${((index+(selected?1:0))/attempt.questions.length)*100}%`}}/></div><section className="game-card"><div className="question-meta"><span className="category">📖 {question.reference||'QUIZ BÍBLICO'}</span><span>PERGUNTA {index+1}<b> / {attempt.questions.length}</b></span></div><div className={`timer ${time<=5?'urgent':''}`} style={{'--time':`${time*24}deg`} as React.CSSProperties}><span>{time}</span></div><h2>{question.prompt}</h2><div className="answers">{question.choices.map((choice,i)=><button key={choice.id} className={feedback?.chosen===choice.id?(feedback.correct?'correct':'wrong'):''} onClick={()=>answer(choice.id)} disabled={!!selected}><b>{String.fromCharCode(65+i)}</b><span>{choice.text}</span><i>{feedback?.chosen===choice.id?(feedback.correct?'✓':'×'):''}</i></button>)}</div>{feedback&&<div className={`feedback ${feedback.correct?'good':'bad'}`}><div><strong>{feedback.correct?`Muito bem! +${feedback.points}`:'Continue firme!'}</strong><p>{feedback.commentary}</p></div><button onClick={next}>{index===attempt.questions.length-1?'FINALIZAR':'PRÓXIMA'} →</button></div>}</section></main>;
}
