import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page, type Route } from "@playwright/test";

function json(route:Route,body:unknown,status=200){return route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)})}
async function mock(page:Page){
  await page.route("**/api/auth/me",route=>json(route,{user:{id:"collector",displayName:"Participante",role:"participant",mustChangePassword:false}}));
  await page.route("**/api/notifications",route=>json(route,{unread:0,notifications:[]}));
  await page.route("**/api/platform/collections",route=>json(route,{summary:{collections:2,completedCollections:0,collectibles:16,ownedCollectibles:1,achievements:2,unlockedAchievements:1},collections:[{id:"biblical-symbols",name:"Símbolos Bíblicos",description:"Avatares inspirados na fé.",coverIcon:"🕊️",progress:{acquired:1,total:8,percent:12,status:"IN_PROGRESS"},items:[{id:"avatar-dove",name:"Avatar Pomba",icon:"🕊️",rarity:"UNCOMMON",origin:"SHOP",originRef:null,owned:true,equipped:true},{id:"avatar-lamp",name:"Avatar Lâmpada",icon:"🪔",rarity:"COMMON",origin:"DAILY",originRef:"daily_challenge_7",owned:false,equipped:false}]},{id:"journey-frames",name:"Molduras da Jornada",description:"Molduras permanentes.",coverIcon:"✨",progress:{acquired:0,total:8,percent:0,status:"IN_PROGRESS"},items:[{id:"frame-light",name:"Moldura Luz",icon:"✨",rarity:"RARE",origin:"ACHIEVEMENT",originRef:"first_steps",owned:false,equipped:false}]}],achievements:[{code:"first_steps",name:"Primeiros Passos",description:"Conclua sua primeira partida oficial.",rarity:"bronze",reward:{xp:50,coins:10},state:"UNLOCKED",unlockedAt:Date.UTC(2026,7,9),progress:{current:1,target:1,percent:100}},{code:"persistent_10",name:"Perseverante",description:"Conclua 10 partidas oficiais.",rarity:"bronze",reward:{xp:50,coins:10},state:"IN_PROGRESS",unlockedAt:null,progress:{current:4,target:10,percent:40}}]}));
}

test("coleções e conquistas são acessíveis e responsivas",async({page})=>{await mock(page);for(const width of [320,360,390,412]){await page.setViewportSize({width,height:844});await page.goto("/recompensas");await expect(page.getByRole("heading",{name:"Minha coleção"})).toBeVisible();await expect(page.getByText("1/16")).toBeVisible();await expect(page.getByText(/Desafio Diário/)).toBeVisible();await expect(page.getByText(/Conquista/).first()).toBeVisible();await expect(page.locator(".reward-art img")).toHaveCount(7);expect(await page.evaluate(()=>document.documentElement.scrollWidth===document.documentElement.clientWidth)).toBe(true)}const audit=await new AxeBuilder({page}).include("main").analyze();expect(audit.violations.filter(item=>["critical","serious"].includes(item.impact||""))).toEqual([])});
