import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test.beforeEach(async ({ page }) => {
  await page.route("**/api/auth/me", route => route.fulfill({ json: { id:"admin",displayName:"Admin",role:"admin",permissions:["events.manage"] } }));
  await page.route("**/api/admin/planning/calendar?**", route => route.fulfill({ json: { generatedAt:Date.now(),from:0,to:1,maxRangeDays:184,timeZone:"America/Sao_Paulo",summary:{totalEvents:2,reservations:1,noEventsNext14Days:false,conflicts:0},editorial:{awaitingReview:3,insights:[{id:"small",title:"Catálogo requer atenção",description:"Prepare novos conteúdos.",severity:"attention"}]},events:[{id:"scheduled",title:"Semana da Bíblia",description:"",status:"SCHEDULED",startsAt:Date.UTC(2026,7,31,23),endsAt:Date.UTC(2026,8,2,2),timeZone:"America/Sao_Paulo",games:[{gameType:"wordle-biblico",selectedCount:1,validCount:1}],reservations:[{gameType:"wordle-biblico",count:1}],checklist:{ready:true,issues:[]},editorHref:"/admin/eventos#event-scheduled"},{id:"draft",title:"Evento incompleto",description:"",status:"DRAFT",startsAt:Date.UTC(2026,8,10),endsAt:Date.UTC(2026,8,11),timeZone:"America/Sao_Paulo",games:[],reservations:[],checklist:{ready:false,issues:[{code:"games_required",label:"Selecione ao menos um jogo."}]},editorHref:"/admin/eventos#event-draft"}] } }));
});

test("calendário desktop mostra agenda, reservas e checklist sem violações axe",async({page})=>{await page.goto("/admin/calendario");await expect(page.getByRole("heading",{name:/Calendário da plataforma/i})).toBeVisible();await expect(page.getByText("Semana da Bíblia").first()).toBeVisible();await expect(page.getByText(/1 conteúdo\(s\) reservado/)).toBeVisible();await expect(page.getByText("✓ Pronto para execução")).toBeVisible();await expect(page.getByText("O que falta preparar?")).toBeVisible();const results=await new AxeBuilder({page}).analyze();expect(results.violations).toEqual([])});
test("calendário móvel não possui overflow impeditivo e mantém controles acessíveis",async({page,isMobile})=>{test.skip(!isMobile,"viewport móvel");await page.goto("/admin/calendario");await expect(page.getByRole("button",{name:"Próximo mês"})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);await expect(page.getByRole("link",{name:/Abrir no Editor/}).first()).toBeVisible()});
