import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const editor = read("app/admin/conteudo/editor/UniversalContentEditor.tsx");
const fields = read("app/admin/conteudo/editor/UniversalFields.tsx");
const model = read("app/admin/conteudo/editor/editor-model.ts");
const page = read("app/admin/conteudo/editor/page.tsx");
const navigation = read("app/navigation.tsx");
const css = read("app/content-editor.css");

test("editor route is active for the existing administrative content permission", () => {
  assert.match(page, /UniversalContentEditor/);
  assert.match(navigation, /label: "Criar conteúdo"[\s\S]*?href: "\/admin\/conteudo\/editor"[\s\S]*?permissions: \["questions\.edit"\]/);
  assert.doesNotMatch(navigation, /label: "Criar conteúdo"[\s\S]*?disabled: true/);
});

test("query contract supports seven aliases and falls back safely to Quiz", () => {
  for (const alias of ["quiz", "wordle", "association", "timeline", "memory", "who-am-i", "three-clues"]) {
    assert.match(model, new RegExp(`"?${alias.replaceAll("-", "\\-")}"?:`));
  }
  assert.match(model, /gameType: gameType \?\? GameType\.QUIZ, invalid: !gameType/);
  assert.match(editor, /O jogo informado não existe/);
  assert.match(editor, /window\.history\.replaceState/);
});

test("editor is generated by the schema registry instead of per-game forms", () => {
  assert.match(editor, /contentSchemas\.map/);
  assert.match(editor, /getContentSchema/);
  assert.match(editor, /schema\.fields\.map/);
  assert.match(editor, /schema\.templates/);
  assert.match(editor, /schema\?\.description/);
  assert.doesNotMatch(editor, /gameType\s*===\s*["']quiz/);
});

test("all universal field types and recursive list/object controls are present", () => {
  for (const component of [
    "TextField", "TextareaField", "SelectField", "NumberField", "BooleanField",
    "ListField", "ObjectField", "ReferenceField", "UniversalFieldRenderer",
  ]) assert.match(fields, new RegExp(`function ${component}|export function ${component}`));
  for (const type of ["textarea", "select", "number", "boolean", "list", "object", "reference"]) {
    assert.match(fields, new RegExp(`field\\.type === "${type}"`));
  }
  assert.match(fields, /Adicionar item/);
  assert.match(fields, /Remover item/);
  assert.match(fields, /Mover item/);
  assert.match(fields, /minimumItems/);
  assert.match(fields, /maximumItems/);
  assert.match(fields, /depth >= 4/);
});

test("templates, dirty confirmation and local reset actions are explicit", () => {
  assert.match(editor, /Aplicar template/);
  assert.match(editor, /Template ativo/);
  assert.match(editor, /window\.confirm/);
  assert.match(editor, /Descartar as alterações locais/);
  assert.match(editor, /Reiniciar/);
  assert.match(editor, /Limpar rascunho local/);
  assert.match(editor, /beforeunload/);
});

test("validation runs live and manually with field and summary feedback", () => {
  assert.match(editor, /setTimeout\(\(\) =>/);
  assert.match(editor, /validateContent\(draft\.gameType, draft\.metadata, draft\.payload\)/);
  assert.match(editor, /Validar conteúdo/);
  assert.match(editor, /ValidationSummary/);
  assert.match(fields, /editor-field-error/);
  assert.match(fields, /role="alert"/);
  assert.match(editor, /aria-live="polite"/);
});

test("preview and metadata remain local and start as DRAFT", () => {
  assert.match(editor, /ContentPreview/);
  assert.match(editor, /Prévia editorial local/);
  assert.match(editor, /Metadados universais/);
  assert.match(editor, /Status editorial/);
  assert.match(model, /status: ContentStatus\.DRAFT/);
  assert.match(fields, /ID opcional/);
  assert.match(fields, /Tipo/);
  assert.match(editor, /Salvar rascunho \(futuro\)/);
  assert.match(editor, /disabled/);
});

test("editor does not persist or issue network writes", () => {
  const source = `${editor}\n${fields}\n${model}`;
  assert.doesNotMatch(source, /\bfetch\s*\(/);
  assert.doesNotMatch(source, /\blocalStorage\b|\bsessionStorage\b|\bindexedDB\b|document\.cookie/);
  assert.doesNotMatch(source, /\bPOST\b|\bPATCH\b|\bDELETE\b/);
});

test("editor layout is responsive, bounded and keyboard accessible", () => {
  assert.match(css, /grid-template-columns:minmax\(0,1\.45fr\)/);
  assert.match(css, /@media\(max-width:980px\)/);
  assert.match(css, /@media\(max-width:650px\)/);
  assert.match(css, /grid-template-columns:1fr/);
  assert.match(css, /min-width:0/);
  assert.match(css, /box-sizing:border-box/);
  assert.match(css, /focus-visible/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(fields, /aria-label=/);
});

test("no migration was added by the local editor sprint", () => {
  const migrations = readdirSync(new URL("../drizzle/", import.meta.url)).filter(name => name.endsWith(".sql"));
  assert.ok(migrations.length > 0);
  assert.equal(migrations.some(name => name.includes("content_editor")), false);
});
