import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
test("authentication is centralized without fast polling",()=>{const provider=read("app/AuthProvider.tsx"),recovery=read("app/AuthRecoveryLink.tsx"),chrome=read("app/ParticipantChrome.tsx"),nav=read("app/LearningQuickNav.tsx"),home=read("app/page.tsx"),logout=read("app/LogoutButton.tsx");assert.match(provider,/fetch\("\/api\/auth\/me"/);assert.match(provider,/createSingleFlight/);assert.doesNotMatch([provider,recovery,chrome,nav,home].join("\n"),/setInterval\([^)]*800|setInterval\(check/);assert.doesNotMatch(chrome,/api\/auth\/me/);assert.doesNotMatch(nav,/api\/auth\/me/);assert.match(chrome,/useAuth\(\)/);assert.match(nav,/useAuth\(\)/);assert.match(home,/setAuthenticatedUser\(result\.user\)/);assert.match(logout,/clearUser\(\)/);assert.match(recovery,/loading \|\| user \|\| !target/);assert.match(chrome,/\["admin", "leader"\]\.includes\(user\.role\)/)});
test("profile consolidates account privacy and logout without extra administration sections",()=>{const profile=read("app/perfil/page.tsx"),sections=read("app/ProfilePrivacySections.tsx"),legacy=read("app/privacidade/conta/page.tsx"),header=read("app/AdminQuickNav.tsx");assert.match(profile,/ProfilePrivacySections/);assert.match(sections,/LogoutButton/);assert.doesNotMatch(sections,/Abrir painel administrativo|<h2>Administração|<h2>Sessão/);assert.match(legacy,/redirect\("\/perfil#conta"\)/);assert.doesNotMatch(header,/AccountMenu|LogoutButton/)});
test("admin active route uses exact or longest route and layout is centered",()=>{const menu=read("app/AdminQuickNav.tsx"),css=read("app/brand-system.css");assert.match(menu,/const activeHref/);assert.match(menu,/sort\(\(a,b\)=>b\.href\.length-a\.href\.length\)/);assert.match(menu,/item\.href===selected/);assert.match(css,/margin-right:auto!important;margin-left:auto!important/);assert.match(css,/padding-top:86px!important/)});
test("AI suggestions are centrally disabled and hidden",()=>{const flag=read("shared/features.ts"),nav=read("app/navigation.tsx"),api=read("functions/api/admin/ai-suggestions.ts");assert.match(flag,/AI_SUGGESTIONS_ENABLED = false/);assert.doesNotMatch(nav,/Sugestões com IA/);assert.match(api,/feature_disabled/);assert.match(api,/if \(!AI_SUGGESTIONS_ENABLED\) return featureDisabled/)});
test("cleanup workflow is explicit local dry-run with backup gate",()=>{const script=read("scripts/cleanup-test-data.mjs");assert.match(script,/--db <arquivo-local>/);assert.match(script,/mode=args\.execute\?"execute":"dry-run"/);assert.match(script,/A execução exige --backup/);assert.match(script,/BEGIN IMMEDIATE/);assert.match(script,/preservedApprovedQuestions:true/)});
test("journey ranking medals and profile keep the participant back action",()=>{const back=read("app/BackNavigation.tsx"),layout=read("app/layout.tsx"),css=read("app/brand-system.css");assert.match(back,/className="global-back"/);assert.match(layout,/BackNavigation/);for(const page of ["journey-page","ranking-page","medals-page"])assert.match(css,new RegExp(`body:has\\(\\.${page}\\) \\.global-back`));assert.match(css,/\.admin-shell\.journey-page,\.admin-shell\.ranking-page,\.admin-shell\.medals-page\{padding-top:70px!important\}/);assert.match(css,/body:has\(\.profile-shell\).*#f5f1fa/)});
test("notifications keeps the participant back action and profile spacing",()=>{const page=read("app/notificacoes/page.tsx"),css=read("app/brand-system.css");assert.match(page,/notification-page/);assert.match(css,/body:has\(\.notification-page\) \.global-back\{display:block!important\}/);assert.match(css,/\.admin-shell\.notification-page\{padding-top:70px!important\}/);assert.match(css,/\.notification-page>\.admin-title\{padding-top:0\}/)});
