import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import test from'node:test';const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
test('global middleware protects mutations and responses',async()=>{const source=await read('functions/_middleware.ts');assert.match(source,/invalid_origin/);assert.match(source,/x-content-type-options/);assert.match(source,/permissions-policy/);assert.match(source,/frame-ancestors/)});
test('sensitive batch operations require password confirmation',async()=>{const[q,u]=await Promise.all([read('functions/api/admin/questions/batch.ts'),read('functions/api/admin/users/batch.ts')]);assert.match(q,/action==='archive'.*passwordOk/s);assert.match(u,/status==='suspended'.*verifyPassword/s);assert.match(q,/organization_id=\?1/);assert.match(u,/organization_id=\?1/)});
test('recovery invalidates sessions and its one-time code',async()=>{const source=await read('functions/api/auth/recover.ts');assert.match(source,/DELETE FROM sessions WHERE user_id/);assert.match(source,/UPDATE account_recovery_codes SET used_at/);assert.match(source,/strongEnough/)});
test('AI suggestions enter the question bank only as drafts',async()=>{const source=await read('functions/api/admin/ai-suggestions.ts');assert.match(source,/'draft','draft'/);assert.match(source,/daily_ai_limit/);assert.match(source,/duplicate_question/)});
test('quiz timing and order are enforced by the server',async()=>{const[start,answer]=await Promise.all([read('functions/api/attempts/start.ts'),read('functions/api/attempts/[id]/answer.ts')]);assert.match(start,/question_order_json/);assert.match(start,/official_attempts_remaining/);assert.match(answer,/serverTimedOut/);assert.match(answer,/invalid_question_order/);assert.doesNotMatch(answer,/const correct = !body\.timedOut/)});
test('exports and API payloads are hardened',async()=>{const[exports,middleware,backup]=await Promise.all([read('functions/api/admin/exports.ts'),read('functions/_middleware.ts'),read('functions/api/admin/backup.ts')]);assert.match(exports,/\\t\\r/);assert.match(exports,/data\.exported/);assert.match(middleware,/payload_too_large/);assert.match(middleware,/no-store, private/);assert.doesNotMatch(backup,/SELECT \* FROM users/);assert.doesNotMatch(backup,/SELECT \* FROM invitations/)});
test('revision restore and round duplication revalidate server state',async()=>{const[revision,duplicate,current,status]=await Promise.all([read('functions/api/admin/questions/[id]/revisions/[revisionId].ts'),read('functions/api/admin/rounds/[id]/duplicate.ts'),read('functions/api/rounds/current.ts'),read('functions/api/rounds/status.ts')]);assert.match(revision,/validateQuestionResult/);assert.match(revision,/invalid_correct_choice/);assert.match(revision,/duplicate_question/);assert.match(duplicate,/validateStoredRound/);assert.match(duplicate,/INSERT INTO choices\(id,question_id,text,position,correct\)/);assert.match(current,/status<>\x27invalid\x27/);assert.match(status,/completedAttempts/)});
test('legacy round seed and invitations preserve integrity and audit',async()=>{const[seed,invites]=await Promise.all([read('functions/api/admin/round-one.ts'),read('functions/api/admin/invitations/[id].ts')]);assert.match(seed,/validateQuestionResult/);assert.match(seed,/validateStoredRound/);assert.match(seed,/'draft'/);assert.match(seed,/round\.seeded_and_published/);assert.doesNotMatch(seed,/JoÃ/);assert.match(invites,/organization_id=\?7/);assert.match(invites,/invitation\.updated/);assert.match(invites,/invitation\.deactivated/);assert.doesNotMatch(invites,/DELETE FROM invitations/)});
