"use client";
import{useEffect,useState}from"react";
const localDate=(value:number)=>{const date=new Date(value-dateOffset(value));return date.toISOString().slice(0,16)};const dateOffset=(value:number)=>new Date(value).getTimezoneOffset()*60000;
export default function Details(){
 const[data,setData]=useState<any>(null),[password,setPassword]=useState(""),[confirming,setConfirming]=useState(false),[editing,setEditing]=useState(false),[message,setMessage]=useState("");const id=typeof window==='undefined'?'':new URL(location.href).searchParams.get('id')||'';
 async function load(){if(!id)return;const r=await fetch(`/api/admin/rounds/${id}`);if(r.status===401||r.status===403){location.href='/';return}setData(await r.json())}useEffect(()=>{load()},[id]);
 async function action(status:string,releaseNow=false){if(status==='closed'&&!confirm('Encerrar esta rodada agora?'))return;const r=await fetch(`/api/admin/rounds/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,releaseNow})});setMessage(r.ok?'Rodada atualizada.':'Não foi possível atualizar.');if(r.ok)load()}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/admin/rounds/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...form,status:data.round.status})});const d=await r.json();if(r.ok){setEditing(false);setMessage('Agendamento atualizado.');load()}else setMessage(d.error==='round_locked'?'Esta rodada já começou ou possui tentativas e não pode mais ser editada.':'Confira as datas e os campos.')}
 async function duplicate(){if(!confirm('Criar uma cópia completa desta rodada?'))return;const r=await fetch(`/api/admin/rounds/${id}/duplicate`,{method:'POST'});const d=await r.json();if(r.ok)location.href=`/admin/rodadas/detalhes?id=${d.roundId}`;else setMessage('Não foi possível duplicar.')}
 async function remove(){const r=await fetch(`/api/admin/rounds/${id}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(r.ok)location.href='/admin/rodadas/lista';else setMessage(d.error==='invalid_password'?'Senha incorreta.':'Não foi possível remover.')}
 if(!data)return <main className="admin-shell"><p>Carregando...</p></main>;const editable=Number(data.attempts?.total||0)===0&&['draft','scheduled'].includes(data.round.status);
 return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">DETALHES DA RODADA</p><h1>{data.round.title}</h1><p>{data.attempts?.participants||0} participante(s) · {data.attempts?.total||0} tentativa(s) · Horário de Brasília</p></section><section className="admin-panel round-detail-actions">{editable&&<button onClick={()=>setEditing(true)}>Editar agendamento</button>}<button onClick={duplicate}>Duplicar</button>{data.round.status==='scheduled'&&<button className="release" onClick={()=>action('active',true)}>Liberar agora</button>}{!['closed','cancelled'].includes(data.round.status)&&<button onClick={()=>action('closed')}>Encerrar</button>}<button className="danger" onClick={()=>setConfirming(true)}>{Number(data.attempts?.total)>0?'Cancelar e arquivar':'Excluir'}</button></section>{message&&<p className="auth-message">{message}</p>}
 {editing&&<form className="admin-panel round-edit-form" onSubmit={save}><h2>Editar rodada futura</h2><label>Título<input name="title" defaultValue={data.round.title} required/></label><label>Tema<input name="theme" defaultValue={data.round.theme} required/></label><label>Descrição<textarea name="description" defaultValue={data.round.description||''}/></label><div><label>Abertura<input name="opensAt" type="datetime-local" defaultValue={localDate(data.round.opens_at)} required/></label><label>Encerramento<input name="closesAt" type="datetime-local" defaultValue={localDate(data.round.closes_at)} required/></label><label>Segundos por pergunta<input name="secondsPerQuestion" type="number" min="15" max="60" defaultValue={data.round.seconds_per_question}/></label></div><p>Os horários serão considerados no fuso de Brasília.</p><footer><button type="button" onClick={()=>setEditing(false)}>Cancelar</button><button className="release">Salvar alterações</button></footer></form>}
 <section className="question-detail-list">{data.questions.map((q:any)=><article className="admin-panel" key={q.id}><small>PERGUNTA {q.position} · {q.reference}</small><h2>{q.prompt}</h2>{q.choices.map((c:any)=><p className={c.correct?'correct-preview':''} key={c.id}>{c.text}</p>)}<em>{q.commentary}</em></article>)}</section>{confirming&&<div className="modal-layer"><section className="admin-panel removal-modal"><h2>{Number(data.attempts?.total)>0?'Cancelar e arquivar rodada?':'Excluir rodada?'}</h2><p>{Number(data.attempts?.total)>0?'Os resultados serão preservados, mas a rodada não aceitará novas tentativas.':'A rodada e suas perguntas serão removidas.'}</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha administrativa"/><div><button onClick={()=>setConfirming(false)}>Voltar</button><button className="danger" onClick={remove}>Confirmar</button></div></section></div>}</main>
}
