import test from"node:test";import assert from"node:assert/strict";
import{createTestDatabase,seedOrganization,seedUser,createSession,createAuthenticatedRequest,createValidRound,responseJson,readAttemptAnswers,withFrozenTime}from"../helpers/integration.mjs";
import{onRequestPost as startAttempt}from"../../functions/api/attempts/start.ts";
import{onRequestPost as answerQuestion}from"../../functions/api/attempts/[id]/answer.ts";
import{onRequestPost as advanceQuestion}from"../../functions/api/attempts/[id]/advance.ts";
import{onRequestPost as finishAttempt}from"../../functions/api/attempts/[id]/finish.ts";

async function setup(t){const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedUser(ctx,{id:"admin-1",role:"admin"});seedUser(ctx,{id:"user-1"});seedUser(ctx,{id:"user-2"});const token=await createSession(ctx,"user-1"),other=await createSession(ctx,"user-2");createValidRound(ctx);return{ctx,token,other}}
const start=(ctx,token,mode="official")=>startAttempt({request:createAuthenticatedRequest("https://test/api/attempts/start",{token,method:"POST",body:{roundId:"round-1",mode}}),env:ctx.env});

test("parallel starts create one official attempt and return resumable state",async t=>{const{ctx,token}=await setup(t),responses=await Promise.all(Array.from({length:5},()=>start(ctx,token)));assert.ok(responses.every(response=>response.status<500));const bodies=await Promise.all(responses.map(responseJson)),ids=new Set(bodies.map(body=>body.attempt.id));assert.equal(ids.size,1);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM attempts WHERE mode='official'").get().total,1);assert.ok(bodies.every(body=>body.attempt.questions.every(question=>question.commentary===undefined&&question.correctIndex===undefined&&question.choices.every(choice=>choice.correct===undefined))))});

test("resume preserves question and choice order without consuming another attempt",async t=>{const{ctx,token}=await setup(t),first=await responseJson(await start(ctx,token)),second=await responseJson(await start(ctx,token));assert.equal(second.attempt.id,first.attempt.id);assert.deepEqual(second.attempt.questions,first.attempt.questions);assert.equal(second.attempt.nextIndex,0);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM attempts").get().total,1);assert.equal(ctx.raw.prepare("SELECT resumed_count FROM attempts").get().resumed_count,1)});

test("feedback reading time does not consume the next question clock",async t=>{const{ctx,token}=await setup(t),base=Date.now(),started=await withFrozenTime(base,async()=>responseJson(await start(ctx,token))),attempt=started.attempt,first=attempt.questions[0];await withFrozenTime(base+1000,()=>answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attempt.id}/answer`,{token,method:"POST",body:{questionId:first.id,choiceId:first.choices[0].id}}),env:ctx.env,params:{id:attempt.id}}));assert.equal(ctx.raw.prepare("SELECT current_question_started_at value FROM attempts WHERE id=?").get(attempt.id).value,null);const advanced=await withFrozenTime(base+16000,async()=>responseJson(await advanceQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attempt.id}/advance`,{token,method:"POST",body:{}}),env:ctx.env,params:{id:attempt.id}})));assert.equal(advanced.nextIndex,1);assert.equal(advanced.remainingSeconds,20);const second=attempt.questions[1];const response=await withFrozenTime(base+18000,()=>answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attempt.id}/answer`,{token,method:"POST",body:{questionId:second.id,choiceId:second.choices[0].id}}),env:ctx.env,params:{id:attempt.id}}));assert.equal(response.status,200);assert.equal(readAttemptAnswers(ctx,attempt.id)[1].response_time_ms,2000)});

test("duplicate answer is idempotent and competing answer cannot replace it",async t=>{const{ctx,token}=await setup(t);const base=Date.now(),startBody=await withFrozenTime(base,async()=>responseJson(await start(ctx,token))),attemptId=startBody.attempt.id,question=startBody.attempt.questions[0],choice=question.choices[0];const first=await withFrozenTime(base+1000,()=>answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attemptId}/answer`,{token,method:"POST",body:{questionId:question.id,choiceId:choice.id,responseTimeMs:-999,points:999999,correct:true,currentStreak:999}}),env:ctx.env,params:{id:attemptId}}));const saved=readAttemptAnswers(ctx,attemptId)[0],again=await withFrozenTime(base+5000,()=>answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attemptId}/answer`,{token,method:"POST",body:{questionId:question.id,choiceId:choice.id}}),env:ctx.env,params:{id:attemptId}})),different=await answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attemptId}/answer`,{token,method:"POST",body:{questionId:question.id,choiceId:question.choices[1].id}}),env:ctx.env,params:{id:attemptId}});assert.equal(first.status,200);assert.equal(again.status,200);assert.equal(different.status,409);assert.equal(readAttemptAnswers(ctx,attemptId).length,1);assert.equal(readAttemptAnswers(ctx,attemptId)[0].choice_id,saved.choice_id);assert.ok(saved.response_time_ms>=900&&saved.response_time_ms<=1100);assert.notEqual(saved.points,999999)});

test("simultaneous duplicate answers persist one row and cross-user access is hidden",async t=>{const{ctx,token,other}=await setup(t),body=await responseJson(await start(ctx,token)),attemptId=body.attempt.id,question=body.attempt.questions[0],payload={questionId:question.id,choiceId:question.choices[0].id},call=()=>answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attemptId}/answer`,{token,method:"POST",body:payload}),env:ctx.env,params:{id:attemptId}}),responses=await Promise.all([call(),call()]);assert.ok(responses.every(response=>response.status<500));assert.equal(readAttemptAnswers(ctx,attemptId).length,1);const denied=await answerQuestion({request:createAuthenticatedRequest(`https://test/api/attempts/${attemptId}/answer`,{token:other,method:"POST",body:payload}),env:ctx.env,params:{id:attemptId}});assert.equal(denied.status,404);assert.equal(readAttemptAnswers(ctx,attemptId).length,1)});

test("fourth official attempt is refused while practice remains separate",async t=>{const{ctx,token}=await setup(t);for(let number=1;number<=3;number++)ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,question_order_json,started_at,completed_at) VALUES(?,?,?,?,?,'completed',?,?,0,1)").run(`done-${number}`,"user-1","round-1",number,"official",`s${number}`,"[]");const fourth=await start(ctx,token);assert.equal(fourth.status,403);assert.equal((await responseJson(fourth)).error,"attempt_limit");const practice=await start(ctx,token,"practice");assert.equal(practice.status,201);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM attempts WHERE mode='official'").get().total,3);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM attempts WHERE mode='practice'").get().total,1)});

test("finish is idempotent and recalculates persisted answers",async t=>{const{ctx,token}=await setup(t),order=Array.from({length:10},(_,i)=>`round-1-q-${i}`);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,question_order_json,started_at) VALUES('finish-me','user-1','round-1',1,'official','in_progress','seed',?,0)").run(JSON.stringify(order));for(let i=0;i<10;i++)ctx.raw.prepare("INSERT INTO attempt_answers(attempt_id,question_id,choice_id,question_order,choice_order_json,correct,response_time_ms,points,answered_at) VALUES('finish-me',?,?,?,?,?,?,?,?)").run(order[i],`${order[i]}-c-0`,i,"[]",i<3?1:0,1000+i,100+i,10000+i);const call=()=>finishAttempt({request:createAuthenticatedRequest("https://test/api/attempts/finish-me/finish",{token,method:"POST",body:{}}),env:ctx.env,params:{id:"finish-me"}}),responses=await Promise.all([call(),call()]);assert.ok(responses.every(response=>response.status===200));const attempt=ctx.raw.prepare("SELECT * FROM attempts WHERE id='finish-me'").get();assert.equal(attempt.status,"completed");assert.equal(attempt.correct_answers,3);assert.equal(attempt.score,1045);assert.equal(attempt.total_time_ms,10045);assert.equal(attempt.max_streak,3);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM audit_logs WHERE entity_id='finish-me' AND action='attempt.completed'").get().total,1)});
