import test from "node:test";import assert from "node:assert/strict";
import {createTestDatabase,seedOrganization,seedUser,createSession,createAuthenticatedRequest,validQuestion,responseJson}from"../helpers/integration.mjs";
import{onRequestPost as createRound}from"../../functions/api/admin/rounds.ts";import{onRequestPatch as editRound}from"../../functions/api/admin/rounds/[id].ts";import{onRequestPost as logout}from"../../functions/api/auth/logout.ts";import{onRequestGet as me}from"../../functions/api/auth/me.ts";import{onRequestPost as aiPost}from"../../functions/api/admin/ai-suggestions.ts";
import{onRequestPost as createTestRound}from"../../functions/api/admin/round-one.ts";
import{onRequestGet as currentRound}from"../../functions/api/rounds/current.ts";
import{createValidRound}from"../helpers/integration.mjs";
const questions=()=>Array.from({length:10},(_,index)=>validQuestion(index));
async function setup(t){const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedOrganization(ctx,{id:"org-2"});seedUser(ctx,{id:"admin",role:"admin"});seedUser(ctx,{id:"participant"});const token=await createSession(ctx,"admin");return{ctx,token}}
const body=(overrides={})=>({title:"Rodada especial",theme:"Milagres",description:"Descrição válida",opensAt:"2026-08-02T09:30",closesAt:"2026-08-09T09:30",secondsPerQuestion:20,officialAttemptLimit:3,roundType:"special",questions:questions(),...overrides});
async function post(ctx,token,payload){return createRound({request:createAuthenticatedRequest("https://test/api/admin/rounds",{token,method:"POST",body:payload}),env:ctx.env})}

test("round schedule blocks partial and total overlap, permits adjacency, cancellation and other organization",async t=>{const{ctx,token}=await setup(t);let first=await post(ctx,token,body());assert.equal(first.status,201);const firstId=(await responseJson(first)).roundId;
 for(const dates of [["2026-08-01T09:30","2026-08-03T09:30"],["2026-08-03T09:30","2026-08-05T09:30"],["2026-08-01T09:30","2026-08-10T09:30"]]){const response=await post(ctx,token,body({title:`Conflito ${dates[0]}`,opensAt:dates[0],closesAt:dates[1]}));assert.equal(response.status,409);assert.equal((await responseJson(response)).error,"round_schedule_conflict")}
 const adjacent=await post(ctx,token,body({title:"Adjacente",opensAt:"2026-08-09T09:30",closesAt:"2026-08-16T09:30"}));assert.equal(adjacent.status,201);
 ctx.raw.prepare("UPDATE rounds SET status='cancelled' WHERE id=?").run(firstId);const replacement=await post(ctx,token,body({title:"Substituta"}));assert.equal(replacement.status,201);
 ctx.raw.prepare("INSERT INTO rounds(id,organization_id,title,theme,status,opens_at,closes_at,official_attempt_limit,seconds_per_question,round_type,created_by,created_at,updated_at) VALUES('other','org-2','Outra','Tema','active',?,?,?,?,?,'admin',0,0)").run(Date.parse("2026-09-01"),Date.parse("2026-09-10"),3,20,"special");
 assert.equal((await post(ctx,token,body({title:"Outra organização",opensAt:"2026-09-02T09:30",closesAt:"2026-09-03T09:30"}))).status,201)});

test("round dates and season rules return actionable codes without partial writes",async t=>{const{ctx,token}=await setup(t),before=ctx.raw.prepare("SELECT COUNT(*) n FROM rounds").get().n;
 for(const [change,error]of[[{opensAt:"inválida"},"invalid_opening_date"],[{closesAt:"inválida"},"invalid_closing_date"],[{closesAt:"2026-08-02T09:30"},"invalid_schedule"],[{roundType:"regular"},"season_required"]]){const response=await post(ctx,token,body(change));assert.equal((await responseJson(response)).error,error)}
 assert.equal(ctx.raw.prepare("SELECT COUNT(*) n FROM rounds").get().n,before);assert.equal((await post(ctx,token,body({roundType:"special"}))).status,201)});

test("editing a scheduled round ignores itself but rejects another occupied period",async t=>{const{ctx,token}=await setup(t),first=await responseJson(await post(ctx,token,body())),second=await responseJson(await post(ctx,token,body({title:"Segunda",opensAt:"2026-08-09T09:30",closesAt:"2026-08-16T09:30"})));
 const own=await editRound({request:createAuthenticatedRequest(`https://test/api/admin/rounds/${first.roundId}`,{token,method:"PATCH",body:{title:"Mesmo período",status:"scheduled"}}),env:ctx.env,params:{id:first.roundId}});assert.equal(own.status,200);
 const conflict=await editRound({request:createAuthenticatedRequest(`https://test/api/admin/rounds/${second.roundId}`,{token,method:"PATCH",body:{opensAt:"2026-08-03T09:30",closesAt:"2026-08-04T09:30",status:"scheduled"}}),env:ctx.env,params:{id:second.roundId}});assert.equal(conflict.status,409);assert.equal((await responseJson(conflict)).error,"round_schedule_conflict")});

test("logout deletes session, expires cookie and subsequent private access is unauthorized",async t=>{const{ctx}=await setup(t);const token=await createSession(ctx,"participant",{token:"logout-token"}),request=createAuthenticatedRequest("https://test/api/auth/logout",{token,method:"POST"}),response=await logout({request,env:ctx.env});assert.equal(response.status,200);assert.match(response.headers.get("set-cookie"),/Max-Age=0/);assert.equal(ctx.raw.prepare("SELECT COUNT(*) n FROM sessions WHERE user_id='participant'").get().n,0);assert.equal((await me({request:createAuthenticatedRequest("https://test/api/auth/me",{token}),env:ctx.env})).status,401)});

test("AI feature flag returns controlled 404 without calling provider",async t=>{const{ctx,token}=await setup(t);let called=false;const response=await aiPost({request:createAuthenticatedRequest("https://test/api/admin/ai-suggestions",{token,method:"POST",body:{theme:"Milagres",count:1}}),env:{...ctx.env,AI:{run:async()=>{called=true;throw new Error("must not run")}}}});assert.equal(response.status,404);assert.equal((await responseJson(response)).error,"feature_disabled");assert.equal(called,false);assert.equal(ctx.raw.prepare("SELECT COUNT(*) n FROM ai_question_suggestions").get().n,0)});
test("test round creates through the real handler once, validates and audits",async t=>{const{ctx,token}=await setup(t);const request=()=>createAuthenticatedRequest("https://test/api/admin/round-one",{token,method:"POST"}),first=await createTestRound({request:request(),env:ctx.env});assert.equal(first.status,201);const data=await responseJson(first),stored=ctx.raw.prepare("SELECT status,round_type FROM rounds WHERE id=?").get(data.roundId);assert.equal(stored.status,"active");assert.equal(stored.round_type,"special");assert.equal(ctx.raw.prepare("SELECT COUNT(*) n FROM questions WHERE round_id=?").get(data.roundId).n,10);assert.equal(ctx.raw.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='round.seeded_and_published'").get().n,1);const again=await createTestRound({request:request(),env:ctx.env});assert.equal(again.status,409);assert.equal((await responseJson(again)).error,"already_exists")});
test("legacy overlapping data deterministically offers another round after the first limit",async t=>{const{ctx}=await setup(t),now=Date.now();createValidRound(ctx,{id:"legacy-a",createdBy:"admin",opensAt:now-1000,closesAt:now+3600000});createValidRound(ctx,{id:"legacy-b",createdBy:"admin",opensAt:now-500,closesAt:now+3600000});for(let number=1;number<=3;number++)ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,correct_answers,total_time_ms,max_streak,started_at,completed_at,question_order_json) VALUES(?,?,?,?,?,'completed',?,?,?,?,?,?,?,?)").run(`done-${number}`,"participant","legacy-a",number,"official",`seed-${number}`,100,1,1000,1,now-1000,now,"[]");const token=await createSession(ctx,"participant",{token:"current-token"}),response=await currentRound({request:createAuthenticatedRequest("https://test/api/rounds/current",{token}),env:ctx.env}),data=await responseJson(response);assert.equal(response.status,200);assert.equal(data.round.id,"legacy-b");assert.equal(data.legacyConflictCount,1)});
