import assert from "node:assert/strict";
import test from "node:test";
import { createTestDatabase,seedOrganization,seedUser,createSession,createAuthenticatedRequest,createValidRound,responseJson,withFrozenTime } from "../helpers/integration.mjs";
import { onRequestGet as journeyStatus } from "../../functions/api/rounds/status.ts";
import { badgeStats,syncBadges } from "../../functions/_lib/badges.ts";
import { onRequestPost as answerQuestion } from "../../functions/api/attempts/[id]/answer.ts";
import { onRequestGet as journeyReview } from "../../functions/api/journey/[roundId].ts";
import { onRequestGet as rankings } from "../../functions/api/rankings.ts";
import { processClosedRoundAwards } from "../../functions/_lib/round-awards.ts";

async function setup(t,{closesAt=Date.now()+3600000}={}){const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedUser(ctx,{id:"admin",role:"admin"});seedUser(ctx,{id:"player"});createValidRound(ctx,{createdBy:"admin",closesAt});const token=await createSession(ctx,"player");return{ctx,token}}

test("status da Jornada distingue tentativa oficial e treino persistidos",async t=>{const{ctx,token}=await setup(t);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,started_at,question_order_json) VALUES('official','player','round-1',1,'official','completed','s',7400,1,'[]'),('training','player','round-1',1,'practice','in_progress','p',0,2,'[]')").run();const response=await journeyStatus({request:createAuthenticatedRequest("https://test/api/rounds/status",{token}),env:ctx.env}),data=await responseJson(response);assert.equal(response.status,200);assert.equal(data.completion.completed,true);assert.equal(data.completion.optionalAttemptsRemaining,2);assert.equal(data.practice.inProgress,true);assert.equal(data.current.practiceAllowed,true)});

test("medalha semanal de pódio só nasce após o encerramento da Jornada",async t=>{const{ctx}=await setup(t);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,correct_answers,total_time_ms,max_streak,started_at,completed_at,question_order_json) VALUES('winner','player','round-1',1,'official','completed','s',9000,10,10000,10,1,2,'[]')").run();assert.equal((await badgeStats(ctx.env,"player")).podiums,0);await syncBadges(ctx.env,"player");assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM user_badges WHERE user_id='player' AND badge_code LIKE 'podium_%'").get().total,0);ctx.raw.prepare("UPDATE rounds SET status='closed',closes_at=1 WHERE id='round-1'").run();assert.equal((await badgeStats(ctx.env,"player")).podiums,1);await syncBadges(ctx.env,"player");assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM user_badges WHERE user_id='player' AND badge_code='podium_1'").get().total,1)});

test("alternativa correta confirmada fora do tempo fica explicitamente identificada",async t=>{const base=Date.now(),{ctx,token}=await setup(t,{closesAt:base+3600000}),order=Array.from({length:10},(_,index)=>`round-1-q-${index}`);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,started_at,question_order_json) VALUES('late','player','round-1',1,'official','in_progress','seed',?,?)").run(base,JSON.stringify(order));const response=await withFrozenTime(base+22000,()=>answerQuestion({request:createAuthenticatedRequest("https://test/api/attempts/late/answer",{token,method:"POST",body:{questionId:order[0],choiceId:`${order[0]}-c-0`}}),env:ctx.env,params:{id:"late"}})),data=await responseJson(response);assert.equal(response.status,200);assert.equal(data.correct,false);assert.equal(data.timedOut,true);assert.match(data.commentary,/após o encerramento do tempo/);assert.equal(ctx.raw.prepare("SELECT correct FROM attempt_answers WHERE attempt_id='late'").get().correct,0);ctx.raw.prepare("UPDATE attempts SET status='completed',score=0,correct_answers=0,total_time_ms=20000,max_streak=0,completed_at=? WHERE id='late'").run(base+22000);ctx.raw.prepare("UPDATE rounds SET status='closed',closes_at=? WHERE id='round-1'").run(base+22000);const review=await journeyReview({request:createAuthenticatedRequest("https://test/api/journey/round-1",{token}),env:ctx.env,params:{roundId:"round-1"}}),reviewData=await responseJson(review);assert.equal(reviewData.questions[0].timedOut,true)});

test("ranking usa uma tentativa real e não combina máximos incompatíveis",async t=>{const{ctx,token}=await setup(t);seedUser(ctx,{id:"rival"});const insert=ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,correct_answers,total_time_ms,max_streak,started_at,completed_at,question_order_json) VALUES(?,?,?,?, 'official','completed','s',?,?,?,?,1,?,'[]')");insert.run("p-best","player","round-1",1,9000,8,50000,8,2);insert.run("p-other","player","round-1",2,8500,10,30000,10,3);insert.run("r-best","rival","round-1",1,9000,9,40000,9,4);const response=await rankings({request:createAuthenticatedRequest("https://test/api/rankings?type=weekly&roundId=round-1",{token}),env:ctx.env}),data=await responseJson(response);assert.equal(response.status,200);assert.deepEqual(data.ranking.map(row=>row.id),["rival","player"]);const player=data.ranking[1];assert.equal(player.score,9000);assert.equal(player.correctAnswers,8);assert.equal(player.totalTimeMs,50000)});

test("encerramento agendado concede pódio e é idempotente",async t=>{const{ctx}=await setup(t);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,correct_answers,total_time_ms,max_streak,started_at,completed_at,question_order_json) VALUES('winner','player','round-1',1,'official','completed','s',9000,10,10000,10,1,2,'[]')").run();ctx.raw.prepare("UPDATE rounds SET status='active',closes_at=1 WHERE id='round-1'").run();const first=await processClosedRoundAwards(ctx.env,2);assert.deepEqual(first,{rounds:1,participants:1,reconciledCancelled:0});assert.equal(ctx.raw.prepare("SELECT status FROM rounds WHERE id='round-1'").get().status,"closed");assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM round_award_processing WHERE round_id='round-1'").get().total,1);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM user_badges WHERE user_id='player' AND badge_code='podium_1'").get().total,1);const second=await processClosedRoundAwards(ctx.env,3);assert.deepEqual(second,{rounds:0,participants:0,reconciledCancelled:0});assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM audit_logs WHERE action='round.awards_processed'").get().total,1)});
