import assert from "node:assert/strict";
import test from "node:test";
import { createTestDatabase,seedOrganization,seedUser,createSession,createAuthenticatedRequest,createValidRound,responseJson } from "../helpers/integration.mjs";
import { onRequestGet as journeyStatus } from "../../functions/api/rounds/status.ts";
import { badgeStats,syncBadges } from "../../functions/_lib/badges.ts";

async function setup(t,{closesAt=Date.now()+3600000}={}){const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedUser(ctx,{id:"admin",role:"admin"});seedUser(ctx,{id:"player"});createValidRound(ctx,{createdBy:"admin",closesAt});const token=await createSession(ctx,"player");return{ctx,token}}

test("status da Jornada distingue tentativa oficial e treino persistidos",async t=>{const{ctx,token}=await setup(t);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,started_at,question_order_json) VALUES('official','player','round-1',1,'official','completed','s',7400,1,'[]'),('training','player','round-1',1,'practice','in_progress','p',0,2,'[]')").run();const response=await journeyStatus({request:createAuthenticatedRequest("https://test/api/rounds/status",{token}),env:ctx.env}),data=await responseJson(response);assert.equal(response.status,200);assert.equal(data.completion.completed,true);assert.equal(data.completion.optionalAttemptsRemaining,2);assert.equal(data.practice.inProgress,true);assert.equal(data.current.practiceAllowed,true)});

test("medalha semanal de pódio só nasce após o encerramento da Jornada",async t=>{const{ctx}=await setup(t);ctx.raw.prepare("INSERT INTO attempts(id,user_id,round_id,attempt_number,mode,status,shuffle_seed,score,correct_answers,total_time_ms,max_streak,started_at,completed_at,question_order_json) VALUES('winner','player','round-1',1,'official','completed','s',9000,10,10000,10,1,2,'[]')").run();assert.equal((await badgeStats(ctx.env,"player")).podiums,0);await syncBadges(ctx.env,"player");assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM user_badges WHERE user_id='player' AND badge_code LIKE 'podium_%'").get().total,0);ctx.raw.prepare("UPDATE rounds SET status='closed',closes_at=1 WHERE id='round-1'").run();assert.equal((await badgeStats(ctx.env,"player")).podiums,1);await syncBadges(ctx.env,"player");assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM user_badges WHERE user_id='player' AND badge_code='podium_1'").get().total,1)});
