import test from"node:test";import assert from"node:assert/strict";
import{createTestDatabase,seedOrganization,seedUser,createSession,createAuthenticatedRequest,validQuestion,createValidRound,responseJson}from"../helpers/integration.mjs";
import{onRequestPost as createQuestion}from"../../functions/api/admin/questions.ts";
import{onRequestPost as createRound}from"../../functions/api/admin/rounds.ts";
import{validateQuestionResult}from"../../functions/_lib/questions.ts";
import{validateStoredRound}from"../../functions/_lib/rounds.ts";

test("question validator executes normalization and strict alternatives",()=>{const base=validQuestion();for(const[input,error]of[[{...base,choices:base.choices.slice(0,3)},"invalid_choice_count"],[{...base,choices:[...base.choices,"extra"]},"invalid_choice_count"],[{...base,choices:["A"," a ","B","C"]},"duplicate_choices"],[{...base,choices:["é","e\u0301","B","C"]},"duplicate_choices"],[{...base,choices:["A"," ","B","C"]},"invalid_choice"],[{...base,prompt:""},"invalid_prompt"],[{...base,prompt:"curta"},"invalid_prompt"],[{...base,prompt:"x".repeat(501)},"invalid_prompt"],[{...base,choices:["x".repeat(301),"B","C","D"]},"invalid_choice"],[{...base,difficulty:"extreme"},"invalid_difficulty"],[[],"invalid_structure"]]){const result=validateQuestionResult(input);assert.equal(result.ok,false);assert.equal(result.error,error)}assert.equal(validateQuestionResult(base).ok,true)});

test("question API persists once per organization and isolates duplicates",async t=>{const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedOrganization(ctx,{id:"org-2"});seedUser(ctx,{id:"admin-1",role:"admin"});seedUser(ctx,{id:"admin-2",organizationId:"org-2",role:"admin"});const token1=await createSession(ctx,"admin-1"),token2=await createSession(ctx,"admin-2"),body=validQuestion();const first=await createQuestion({request:createAuthenticatedRequest("https://test/api/admin/questions",{token:token1,method:"POST",body}),env:ctx.env});assert.equal(first.status,201);const duplicate=await createQuestion({request:createAuthenticatedRequest("https://test/api/admin/questions",{token:token1,method:"POST",body}),env:ctx.env});assert.equal(duplicate.status,409);const other=await createQuestion({request:createAuthenticatedRequest("https://test/api/admin/questions",{token:token2,method:"POST",body}),env:ctx.env});assert.equal(other.status,201);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM question_bank WHERE organization_id='org-1'").get().total,1);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM question_bank WHERE organization_id='org-2'").get().total,1);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM question_bank_choices").get().total,8)});

test("round creation rejects bad configuration without partial writes and audits valid publication",async t=>{const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedUser(ctx,{id:"admin-1",role:"admin"});const token=await createSession(ctx,"admin-1"),questions=Array.from({length:10},(_,i)=>validQuestion(i)),base={title:"Rodada Nova",theme:"Milagres",roundType:"special",opensAt:"2026-07-19T09:30",closesAt:"2026-07-26T09:30",secondsPerQuestion:20,officialAttemptLimit:3,questions};for(const change of[{questions:questions.slice(0,9)},{questions:[...questions,validQuestion(11)]},{secondsPerQuestion:5},{secondsPerQuestion:90},{officialAttemptLimit:0},{officialAttemptLimit:9},{closesAt:"2026-07-19T09:30"}]){const response=await createRound({request:createAuthenticatedRequest("https://test/api/admin/rounds",{token,method:"POST",body:{...base,...change}}),env:ctx.env});assert.ok(response.status>=400);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM rounds").get().total,0)}const response=await createRound({request:createAuthenticatedRequest("https://test/api/admin/rounds",{token,method:"POST",body:base}),env:ctx.env});assert.equal(response.status,201);const data=await responseJson(response);assert.equal((await validateStoredRound(ctx.env,data.roundId,"org-1")).ok,true);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM questions WHERE round_id=?").get(data.roundId).total,10);assert.equal(ctx.raw.prepare("SELECT COUNT(*) total FROM audit_logs WHERE action='round.created_and_scheduled'").get().total,1)});

test("stored round validation observes persisted corruption",async t=>{const ctx=createTestDatabase();t.after(ctx.close);seedOrganization(ctx);seedUser(ctx,{id:"admin-1",role:"admin"});createValidRound(ctx);assert.equal((await validateStoredRound(ctx.env,"round-1","org-1")).ok,true);ctx.raw.prepare("UPDATE questions SET active=0 WHERE id='round-1-q-0'").run();assert.equal((await validateStoredRound(ctx.env,"round-1","org-1")).error,"invalid_round_questions");ctx.raw.prepare("UPDATE questions SET active=1 WHERE id='round-1-q-0'").run();ctx.raw.prepare("UPDATE choices SET text='Alternativa B 1' WHERE id='round-1-q-0-c-0'").run();assert.equal((await validateStoredRound(ctx.env,"round-1","org-1")).error,"invalid_round_choices")});
