import{requireUser,type AppEnv}from"../_lib/auth";import{BADGES}from"../_lib/badges";import{json}from"../_lib/security";import{enforceRateLimit,requestFingerprint}from"../_lib/abuse";
type Notice={key:string;type:string;icon:string;title:string;message:string;href:string;createdAt:number;priority?:string};
async function notices(env:AppEnv,user:any){const now=Date.now(),items:Notice[]=[];
  const announcements:any=await env.DB.prepare(`SELECT id,title,body,priority,publish_at publishAt FROM announcements WHERE organization_id=?1 AND active=1 AND publish_at<=?2 AND (expires_at IS NULL OR expires_at>?2) AND (audience='all' OR audience=?3) ORDER BY publish_at DESC LIMIT 30`).bind(user.organizationId,now,['admin','leader'].includes(user.role)?'leaders':'participants').all();
  for(const row of announcements.results as any[])items.push({key:`announcement-${row.id}`,type:'announcement',icon:row.priority==='urgent'?'🚨':row.priority==='important'?'📣':'💬',title:row.title,message:row.body,href:'/notificacoes',createdAt:Number(row.publishAt),priority:row.priority});
  const current:any=await env.DB.prepare(`SELECT r.id,r.title,r.opens_at opensAt,r.closes_at closesAt,COUNT(CASE WHEN a.mode='official' AND a.status='completed' THEN 1 END) attempts FROM rounds r LEFT JOIN attempts a ON a.round_id=r.id AND a.user_id=?1 WHERE r.organization_id=?2 AND r.opens_at<=?3 AND r.closes_at>?3 AND r.status IN ('scheduled','active') GROUP BY r.id ORDER BY r.opens_at DESC LIMIT 1`).bind(user.id,user.organizationId,now).first();
  if(current){if(Number(current.attempts)===0)items.push({key:`round-open-${current.id}`,type:'round',icon:'📖',title:'A Jornada está aberta',message:`${current.title} já está disponível para jogar.`,href:'/jogar',createdAt:Number(current.opensAt)});if(Number(current.closesAt)-now<=24*60*60*1000)items.push({key:`round-closing-${current.id}`,type:'deadline',icon:'⏳',title:'A Jornada termina em breve',message:`Restam menos de 24 horas para concluir ou melhorar seu resultado em ${current.title}.`,href:'/jogar',createdAt:now})}
  const next:any=await env.DB.prepare("SELECT id,title,opens_at opensAt FROM rounds WHERE organization_id=?1 AND status='scheduled' AND opens_at>?2 AND opens_at<=?3 ORDER BY opens_at LIMIT 1").bind(user.organizationId,now,now+48*60*60*1000).first();if(next)items.push({key:`round-next-${next.id}`,type:'schedule',icon:'🗓️',title:'Nova Jornada se aproxima',message:`${next.title} começa em até 48 horas.`,href:'/',createdAt:Number(next.opensAt)});
  const earned:any=await env.DB.prepare("SELECT badge_code,earned_at FROM user_badges WHERE user_id=?1 AND earned_at>=?2 ORDER BY earned_at DESC LIMIT 20").bind(user.id,now-30*24*60*60*1000).all();for(const row of earned.results as any[]){const badge=BADGES.find(item=>item.code===row.badge_code);if(badge)items.push({key:`badge-${badge.code}`,type:'badge',icon:badge.icon,title:'Medalha conquistada',message:`Você desbloqueou ${badge.name} · nível ${badge.level} (${badge.tier}).`,href:'/medalhas',createdAt:Number(row.earned_at)})}
  const read:any=await env.DB.prepare("SELECT notification_key FROM notification_receipts WHERE user_id=?1").bind(user.id).all(),seen=new Set((read.results as any[]).map(row=>row.notification_key));return items.sort((a,b)=>b.createdAt-a.createdAt).map(item=>({...item,read:seen.has(item.key)}));
}
export const onRequestGet=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),notifications=await notices(env,user);return json({notifications,unread:notifications.filter(item=>!item.read).length})}catch(response){if(response instanceof Response)return response;throw response;}};
export const onRequestPost=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),fingerprint=await requestFingerprint(request),retry=await enforceRateLimit(env,`notifications:${user.id}:${fingerprint}`,60,10*60*1000);if(retry)return json({error:'too_many_requests',retryAfter:retry},429,{'retry-after':String(retry)});const body:any=await request.json(),now=Date.now(),items=await notices(env,user);if(body.all){const statements=[...items.filter(item=>!item.read).map(item=>env.DB.prepare("INSERT OR REPLACE INTO notification_receipts (user_id,notification_key,read_at) VALUES (?1,?2,?3)").bind(user.id,item.key,now)),env.DB.prepare("DELETE FROM notification_receipts WHERE user_id=?1 AND read_at<?2").bind(user.id,now-90*24*60*60*1000)];await env.DB.batch(statements);return json({ok:true})}const key=String(body.key||'');if(!key||key.length>120||!items.some(item=>item.key===key))return json({error:'invalid_key'},400);await env.DB.prepare("INSERT OR REPLACE INTO notification_receipts (user_id,notification_key,read_at) VALUES (?1,?2,?3)").bind(user.id,key,now).run();return json({ok:true})}catch(response){if(response instanceof Response)return response;throw response;}};
