import{requireUser,type AppEnv}from"../_lib/auth";import{json}from"../_lib/security";import{enforceRateLimit,requestFingerprint}from"../_lib/abuse";
type Notice={key:string;type:string;icon:string;title:string;message:string;href:string;createdAt:number;priority?:string};
async function notices(env:AppEnv,user:any){const now=Date.now(),items:Notice[]=[];
  const announcements:any=await env.DB.prepare(`SELECT id,title,body,priority,publish_at publishAt FROM announcements WHERE organization_id=?1 AND active=1 AND publish_at<=?2 AND (expires_at IS NULL OR expires_at>?2) AND (audience='all' OR audience=?3) ORDER BY publish_at DESC LIMIT 30`).bind(user.organizationId,now,['admin','leader'].includes(user.role)?'leaders':'participants').all();
  for(const row of announcements.results as any[])items.push({key:`announcement-${row.id}`,type:'announcement',icon:row.priority==='urgent'?'🚨':row.priority==='important'?'📣':'💬',title:row.title,message:row.body,href:'/notificacoes',createdAt:Number(row.publishAt),priority:row.priority});
  const read:any=await env.DB.prepare("SELECT notification_key FROM notification_receipts WHERE user_id=?1").bind(user.id).all(),seen=new Set((read.results as any[]).map(row=>row.notification_key));return items.sort((a,b)=>b.createdAt-a.createdAt).map(item=>({...item,read:seen.has(item.key)}));
}
export const onRequestGet=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),notifications=await notices(env,user);return json({notifications,unread:notifications.filter(item=>!item.read).length})}catch(response){if(response instanceof Response)return response;throw response;}};
export const onRequestPost=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),fingerprint=await requestFingerprint(request),retry=await enforceRateLimit(env,`notifications:${user.id}:${fingerprint}`,60,10*60*1000);if(retry)return json({error:'too_many_requests',retryAfter:retry},429,{'retry-after':String(retry)});const body:any=await request.json(),now=Date.now(),items=await notices(env,user);if(body.all){const statements=[...items.filter(item=>!item.read).map(item=>env.DB.prepare("INSERT OR REPLACE INTO notification_receipts (user_id,notification_key,read_at) VALUES (?1,?2,?3)").bind(user.id,item.key,now)),env.DB.prepare("DELETE FROM notification_receipts WHERE user_id=?1 AND read_at<?2").bind(user.id,now-90*24*60*60*1000)];await env.DB.batch(statements);return json({ok:true})}const key=String(body.key||'');if(!key||key.length>120||!items.some(item=>item.key===key))return json({error:'invalid_key'},400);await env.DB.prepare("INSERT OR REPLACE INTO notification_receipts (user_id,notification_key,read_at) VALUES (?1,?2,?3)").bind(user.id,key,now).run();return json({ok:true})}catch(response){if(response instanceof Response)return response;throw response;}};
