import { requireUser, type AppEnv } from "../_lib/auth";import { json } from "../_lib/security";
const name=`CASE WHEN u.use_nickname_in_ranking=1 AND u.nickname IS NOT NULL THEN u.nickname ELSE u.display_name END`;
export const onRequestGet=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),url=new URL(request.url),type=url.searchParams.get('type')||'weekly',now=Date.now(),bindings:any[]=[user.organizationId];let query='',unit='pts',direction='desc';
if(type==='weekly'){const roundId=url.searchParams.get('roundId')||(await env.DB.prepare(`SELECT id FROM rounds WHERE organization_id=?1 AND opens_at<=?2 ORDER BY opens_at DESC LIMIT 1`).bind(user.organizationId,now).first<any>())?.id;if(!roundId)return json({ranking:[],unit,direction});bindings.push(roundId);query=`SELECT u.id,${name} displayName,MAX(a.score) score,MAX(a.correct_answers) correctAnswers,MIN(a.total_time_ms) totalTimeMs FROM users u JOIN attempts a ON a.user_id=u.id WHERE u.organization_id=?1 AND a.round_id=?2 AND a.mode='official' AND a.status='completed' GROUP BY u.id ORDER BY score DESC,correctAnswers DESC,totalTimeMs ASC LIMIT 100`}
else if(type==='season'){const season:any=url.searchParams.get('seasonId')?await env.DB.prepare(`SELECT id,status FROM seasons WHERE id=?1 AND organization_id=?2`).bind(url.searchParams.get('seasonId'),user.organizationId).first():await env.DB.prepare(`SELECT id,status FROM seasons WHERE organization_id=?1 AND status IN ('active','closed') ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END,ends_at DESC LIMIT 1`).bind(user.organizationId).first();if(!season)return json({ranking:[],unit,direction});bindings.push(season.id);query=season.status==='closed'?`SELECT u.id,${name} displayName,ss.score,ss.rounds_played roundsPlayed,ss.position FROM season_snapshots ss JOIN users u ON u.id=ss.user_id WHERE u.organization_id=?1 AND ss.season_id=?2 ORDER BY ss.position LIMIT 100`:`WITH best AS (SELECT a.user_id,a.round_id,MAX(a.score) score FROM attempts a JOIN rounds r ON r.id=a.round_id WHERE a.mode='official' AND a.status='completed' AND r.season_id=?2 GROUP BY a.user_id,a.round_id) SELECT u.id,${name} displayName,SUM(best.score) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id ORDER BY score DESC LIMIT 100`}
else if(type==='average'){query=`WITH best AS (SELECT user_id,round_id,MAX(score) score FROM attempts WHERE mode='official' AND status='completed' GROUP BY user_id,round_id) SELECT u.id,${name} displayName,ROUND(AVG(best.score)) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score DESC LIMIT 100`}
else if(type==='accuracy'){unit='%';query=`WITH best AS (SELECT user_id,round_id,MAX(correct_answers) correct FROM attempts WHERE mode='official' AND status='completed' GROUP BY user_id,round_id) SELECT u.id,${name} displayName,ROUND(AVG(best.correct)*10,1) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score DESC,roundsPlayed DESC LIMIT 100`}
else if(type==='speed'){unit='s';direction='asc';query=`WITH best AS (SELECT user_id,round_id,MIN(total_time_ms) time FROM attempts WHERE mode='official' AND status='completed' AND correct_answers>=8 GROUP BY user_id,round_id) SELECT u.id,${name} displayName,ROUND(AVG(best.time)/1000,1) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score ASC LIMIT 100`}
else if(type==='events'){query=`WITH best AS (SELECT a.user_id,a.round_id,MAX(a.score) score FROM attempts a JOIN rounds r ON r.id=a.round_id WHERE a.mode='official' AND a.status='completed' AND r.round_type<>'regular' GROUP BY a.user_id,a.round_id) SELECT u.id,${name} displayName,SUM(best.score) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id ORDER BY score DESC LIMIT 100`}
else{query=`WITH best AS (SELECT user_id,round_id,MAX(score) score FROM attempts WHERE mode='official' AND status='completed' GROUP BY user_id,round_id) SELECT u.id,${name} displayName,SUM(best.score) score,COUNT(*) roundsPlayed FROM users u JOIN best ON best.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id ORDER BY score DESC LIMIT 100`}
const {results}=await env.DB.prepare(query).bind(...bindings).all();return json({ranking:results,unit,direction,minimumRounds:['average','accuracy','speed'].includes(type)?3:1});}catch(response){if(response instanceof Response)return response;throw response;}};
