import { requireUser, type AppEnv } from "../_lib/auth";import { json } from "../_lib/security";import { BEST_ATTEMPTS_CTE } from "../_lib/ranking";
const name=`CASE WHEN u.use_nickname_in_ranking=1 AND u.nickname IS NOT NULL THEN u.nickname ELSE u.display_name END`;
export const onRequestGet=async({request,env}:{request:Request;env:AppEnv})=>{try{const user:any=await requireUser(request,env),url=new URL(request.url),type=url.searchParams.get('type')||'weekly',now=Date.now(),bindings:any[]=[user.organizationId];let query='',unit='pts',direction='desc';
if(type==='weekly'){const roundId=url.searchParams.get('roundId')||(await env.DB.prepare(`SELECT id FROM rounds WHERE organization_id=?1 AND opens_at<=?2 ORDER BY opens_at DESC LIMIT 1`).bind(user.organizationId,now).first<any>())?.id;if(!roundId)return json({ranking:[],unit,direction});bindings.push(roundId);query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,b.score,b.correct_answers correctAnswers,b.total_time_ms totalTimeMs FROM users u JOIN best_attempts b ON b.user_id=u.id WHERE u.organization_id=?1 AND b.round_id=?2 ORDER BY b.score DESC,b.correct_answers DESC,b.total_time_ms ASC,b.completed_at ASC,b.id ASC LIMIT 100`}
else if(type==='season'){const season:any=url.searchParams.get('seasonId')?await env.DB.prepare(`SELECT id,status FROM seasons WHERE id=?1 AND organization_id=?2`).bind(url.searchParams.get('seasonId'),user.organizationId).first():await env.DB.prepare(`SELECT id,status FROM seasons WHERE organization_id=?1 AND status IN ('active','closed') ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END,ends_at DESC LIMIT 1`).bind(user.organizationId).first();if(!season)return json({ranking:[],unit,direction});bindings.push(season.id);query=season.status==='closed'?`SELECT u.id,${name} displayName,ss.score,ss.rounds_played roundsPlayed,ss.position FROM season_snapshots ss JOIN users u ON u.id=ss.user_id WHERE u.organization_id=?1 AND ss.season_id=?2 ORDER BY ss.position LIMIT 100`:`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,SUM(b.score) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id JOIN rounds r ON r.id=b.round_id WHERE u.organization_id=?1 AND r.season_id=?2 GROUP BY u.id ORDER BY score DESC LIMIT 100`}
else if(type==='average'){query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,ROUND(AVG(b.score)) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score DESC LIMIT 100`}
else if(type==='accuracy'){unit='%';query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,ROUND(AVG(b.correct_answers)*10,1) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score DESC,roundsPlayed DESC LIMIT 100`}
else if(type==='speed'){unit='s';direction='asc';query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,ROUND(AVG(b.total_time_ms)/1000,1) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id WHERE u.organization_id=?1 AND b.correct_answers>=8 GROUP BY u.id HAVING COUNT(*)>=3 ORDER BY score ASC LIMIT 100`}
else if(type==='events'){query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,SUM(b.score) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id JOIN rounds r ON r.id=b.round_id WHERE u.organization_id=?1 AND r.round_type<>'regular' GROUP BY u.id ORDER BY score DESC LIMIT 100`}
else{query=`WITH ${BEST_ATTEMPTS_CTE} SELECT u.id,${name} displayName,SUM(b.score) score,COUNT(*) roundsPlayed FROM users u JOIN best_attempts b ON b.user_id=u.id WHERE u.organization_id=?1 GROUP BY u.id ORDER BY score DESC LIMIT 100`}
const {results}=await env.DB.prepare(query).bind(...bindings).all();return json({ranking:results,unit,direction,minimumRounds:['average','accuracy','speed'].includes(type)?3:1});}catch(response){if(response instanceof Response)return response;throw response;}};
