"use client";
import { useEffect, useState } from "react";

export default function ArchivedQuestions() {
  const [items, setItems] = useState<any[]>([]), [page, setPage] = useState(1), [totalPages, setTotalPages] = useState(1), [total, setTotal] = useState(0), [query, setQuery] = useState(""), [message, setMessage] = useState("");
  async function load() { const params = new URLSearchParams({ archived: "1", page: String(page), limit: "50", q: query }); const response = await fetch(`/api/admin/questions?${params}`); if (!response.ok) { location.href = "/admin/perguntas"; return; } const data = await response.json(); setItems(data.questions || []); setTotal(data.total || 0); setTotalPages(data.totalPages || 1); }
  useEffect(() => { const timer = setTimeout(load, 200); return () => clearTimeout(timer); }, [page, query]);
  async function restore(item: any) { if (!confirm(`Restaurar “${item.prompt}” como rascunho?`)) return; const response = await fetch(`/api/admin/questions/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ restore: true }) }); setMessage(response.ok ? "Pergunta restaurada como rascunho." : "Não foi possível restaurar."); if (response.ok) load(); }
  return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">HISTÓRICO DO ACERVO</p><h1>Perguntas <em>arquivadas</em></h1><p>{total} pergunta(s) fora do acervo ativo. A restauração retorna o conteúdo para rascunho.</p></section><section className="bank-toolbar admin-panel"><input placeholder="Pesquisar enunciado ou referência" value={query} onChange={event => { setPage(1); setQuery(event.target.value); }}/><a className="similar-link" href="/admin/perguntas">VOLTAR AO ACERVO</a></section>{message && <p className="auth-message">{message}</p>}<section className="archive-grid">{items.map(item => <article className="admin-panel archive-card" key={item.id}><small>{item.reference || item.book || "Sem referência"} · {item.theme}</small><h2>{item.prompt}</h2><p>{item.commentary || "Sem comentário."}</p><footer><button onClick={() => restore(item)}>RESTAURAR COMO RASCUNHO</button></footer></article>)}{!items.length && <div className="admin-panel bank-empty">Nenhuma pergunta arquivada encontrada.</div>}</section><nav className="bank-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>← Anterior</button><span>Página <b>{page}</b> de <b>{totalPages}</b></span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Próxima →</button></nav></main>;
}
