"use client";
import { useEffect, useState } from "react";
import QuestionEditorModal from "../QuestionEditorModal";

const labels: Record<string, string> = { draft: "Rascunho", in_review: "Aguardando revisão", approved: "Aprovada", changes_requested: "Ajustes solicitados" };
export default function ReviewQueue() {
  const [items, setItems] = useState<any[]>([]), [status, setStatus] = useState("in_review"), [message, setMessage] = useState(""), [note, setNote] = useState(""), [target, setTarget] = useState<any>(null), [editing, setEditing] = useState<string | null>(null);
  async function load() { const response = await fetch(`/api/admin/questions?${new URLSearchParams({ reviewStatus: status })}`); if (!response.ok) { location.href = "/admin"; return; } setItems((await response.json()).questions || []); }
  useEffect(() => { load(); }, [status]);
  async function action(item: any, actionName: string) { if (actionName === "request_changes") { setTarget(item); return; } const response = await fetch(`/api/admin/questions/${item.id}/review`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: actionName }) }), data = await response.json(); setMessage(response.ok ? "Fluxo editorial atualizado." : data.error === "forbidden" ? "Seu perfil não possui permissão para esta ação." : "Não foi possível realizar a transição."); if (response.ok) load(); }
  async function requestChanges() { const response = await fetch(`/api/admin/questions/${target.id}/review`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "request_changes", note }) }); setMessage(response.ok ? "Ajustes solicitados ao editor." : "Informe claramente os ajustes necessários."); if (response.ok) { setTarget(null); setNote(""); load(); } }
  return <main className="admin-shell"><section className="admin-title"><p className="eyebrow">FLUXO EDITORIAL</p><h1>Revisão de <em>perguntas</em></h1><p>Somente questões aprovadas ficam disponíveis para novas rodadas.</p></section>{message && <p className="auth-message">{message}</p>}<nav className="review-tabs">{Object.entries(labels).map(([value, label]) => <button className={status === value ? "active" : ""} onClick={() => setStatus(value)} key={value}>{label}</button>)}</nav><section className="review-grid">{items.map(item => <article className="admin-panel" key={item.id}><small>{item.reference || item.book || "Sem referência"} · {labels[item.review_status] || item.review_status}</small><h2>{item.prompt}</h2><p>{item.theme} · {item.category || "Sem categoria"} · versão {item.version || 1}</p><footer><button onClick={() => setEditing(item.id)}>EDITAR AQUI</button>{["draft", "changes_requested"].includes(item.review_status) && <button onClick={() => action(item, "submit")}>ENVIAR PARA REVISÃO</button>}{item.review_status === "in_review" && <><button className="approve" onClick={() => action(item, "approve")}>APROVAR</button><button className="changes" onClick={() => action(item, "request_changes")}>SOLICITAR AJUSTES</button></>}</footer></article>)}{!items.length && <section className="admin-panel bank-empty">Nenhuma pergunta nesta etapa.</section>}</section>{target && <div className="modal-layer"><section className="admin-panel removal-modal"><h2>Solicitar ajustes</h2><p>{target.prompt}</p><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Descreva os ajustes necessários" autoFocus/><div><button onClick={() => setTarget(null)}>Cancelar</button><button className="danger" disabled={note.trim().length < 3} onClick={requestChanges}>ENVIAR AO EDITOR</button></div></section></div>}{editing && <QuestionEditorModal id={editing} onClose={() => setEditing(null)} onChanged={() => { setMessage("Pergunta atualizada. Alterações de conteúdo retornam a pergunta para rascunho."); load(); }}/>}</main>;
}
