// Curated, accent-insensitive PT-BR vocabulary for Wordle guesses.
// Answers remain server-side and are not derived from this list in the browser.
// Keep entries normalized (A-Z), between five and seven letters, and review additions editorially.
const GENERAL_PORTUGUESE_WORDS = `
ABRACO ABRIGO ABRIR ACASO ACEITE ACERTO ACHADO ACOES ACORDO ADORAR AJUDAR ALEGRE ALENTO AMAVEL AMIGOS AMOROSO ANEIS ANIMAL ANTES APOIAR ARVORE ASSIM AVANCO AVES AZEITE
BAIXAR BARCO BEIJAR BELEZA BEMVINDO BONDADE BUSCAR CABECA CAMINHO CANSAR CANTO CARTAS CERTO CHAMAR CHAVE CHEGAR CIDADE CLARO COISAS COMIDA CORAGEM CORRER CUIDAR CULTIVAR
DANIEL DEITAR DEPOIS DESEJO DEVOTO DIGNO DIREITO DOADOR DOCE DOMINGO DORMIR ENSINO ENTRAR ESCOLA ESPADA ESPERA ESPERAR ESPIRITO ESTRELA EXEMPLO FALAR FAMILIA FARINHA FAZER FELIZ FIRME FLORES FOLHAS FORTE FRATERNO
GANHAR GENTIL GLORIA GRATO GUARDAR GUIAR HISTORIA HONESTO HUMILDE IDEIAS IGREJA IRMAOS JARDIM JOVENS JUSTICA LEALDADE LEITURA LEMBRAR LIBERTO LIVROS LOUVAR LUGAR LUZES
MANHA MANSO MENSAGEM MESTRE MILAGRE MOMENTO MORADA MUNDO NASCER NAVIO NOBRE NOVO OBRAS OFERTA OLHAR ORACAO ORDEM OUVIR PALAVRA PASSOS PASTOR PEDIDO PENSAR PERDAO PESSOA PORTAS POVOS PRANTO PRESENTE PROMESSA PUREZA
RAZAO RECEBER REINO RESPOSTA ROCHA SABEDOR SABER SAUDE SEGUIR SENHOR SERENO SERVIR SINAIS SONHOS SORRIR TEMPLO TEMPO TERRA TESTE TRABALHO UNIDOS VERDADE VERSOS VIAGEM VIDA VIGIAR VITORIA VIVER VOZES
`.trim().split(/\s+/);

const BIBLICAL_WORDS = `
ABRAAO ABRAO ACABE ADONAI AGUAS ALTAR AMADO ANJOS ASAFE BACIA BETEL CAIM CANAA CEDRO CEIFA CINTO COBRE COROA CRISTO DARIO DAVI ELIAS ELISEU ESTER EXODO FARAO FELIX FILHO GALILEIA GIDEAO GRACA HERODES ISAAC ISAI ISRAEL JAIRO JESUS JOABE JOAO JONAS JORDAO JOSE JOSUE JUDAS JUDEA LABAO LANCA LAZARO LIRIO LUCAS MANASSE MANTO MARIA MOABE MOISES NACAO NARDO NAZARE NOEMI NOITE NUVEM ODRES PAULO PEDRA PEDRO PEIXE POMBA PRAGA RAMOS REBECA RUBEN SALEM SAMUEL SANSAO SANTO SAULO SILAS SIMAO SINAI SIRIA TABOR TARSO TENDA TIAGO TIMOTEO TRIBO TRIGO TRONO URIAS VASOS VINHO VISAO
`.trim().split(/\s+/);

export const WORDLE_ACCEPTED_GUESSES = new Set(
  [...GENERAL_PORTUGUESE_WORDS, ...BIBLICAL_WORDS]
    .filter(word => /^[A-Z]{5,7}$/.test(word)),
);

export function isBundledWordleGuess(value: string) {
  return WORDLE_ACCEPTED_GUESSES.has(value);
}
