"use client";
import { useState } from "react";

const blankQuestion = () => ({ reference: "", prompt: "", choices: ["", "", "", ""], correctIndex: 0, commentary: "" });

export default function RoundsAdmin() {
  const [questions, setQuestions] = useState(() => Array.from({ length: 10 }, blankQuestion)); const [message, setMessage] = useState(""); const [busy,setBusy]=useState(false);
  function updateQuestion(index:number, patch:any){setQuestions(current=>current.map((q,i)=>i===index?{...q,...patch}:q));}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/rounds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:data.title,theme:data.theme,description:data.description,opensAt:data.opensAt,closesAt:data.closesAt,questions})});setMessage(response.ok?"Rodada agendada com sucesso.":"Confira os dados e as dez perguntas.");setBusy(false);}
  return <main className="admin-shell"><header className="admin-head"><div className="brand"><span className="brand-dot">✦</span> CONTE OS FEITOS</div><a href="/admin">Acessos</a></header><section className="admin-title"><p className="eyebrow">NOVA RODADA</p><h1>Prepare a próxima <em>competição</em></h1><p>Ela permanecerá bloqueada até a data e o horário definidos.</p></section>
  <form className="round-form" onSubmit={submit}><section className="admin-panel round-basics"><label>Título<input name="title" required placeholder="Ex.: Contem o que Deus fez" /></label><label>Tema<input name="theme" required placeholder="Testemunhos e milagres" /></label><label className="wide">Apresentação<textarea name="description" placeholder="Uma breve introdução para os participantes" /></label><label>Liberação<input name="opensAt" type="datetime-local" required /></label><label>Encerramento<input name="closesAt" type="datetime-local" required /></label></section>
  <div className="question-builder">{questions.map((q,index)=><section className="admin-panel edit-question" key={index}><div className="panel-title"><div><small>PERGUNTA {index+1}</small><h2>{q.prompt||"Nova pergunta"}</h2></div></div><label>Referência<input value={q.reference} onChange={e=>updateQuestion(index,{reference:e.target.value})} placeholder="Ex.: João 9" /></label><label>Enunciado<textarea required value={q.prompt} onChange={e=>updateQuestion(index,{prompt:e.target.value})} /></label><div className="choice-editor">{q.choices.map((choice,i)=><label key={i} className={q.correctIndex===i?"chosen":""}><input type="radio" name={`correct-${index}`} checked={q.correctIndex===i} onChange={()=>updateQuestion(index,{correctIndex:i})} /><span>{String.fromCharCode(65+i)}</span><input required value={choice} onChange={e=>{const choices=[...q.choices];choices[i]=e.target.value;updateQuestion(index,{choices});}} placeholder={`Alternativa ${String.fromCharCode(65+i)}`} /></label>)}</div><label>Comentário após a resposta<textarea value={q.commentary} onChange={e=>updateQuestion(index,{commentary:e.target.value})} /></label></section>)}</div><div className="publish-bar"><span>{message||"10 perguntas · 3 tentativas oficiais · 15 segundos"}</span><button className="primary" disabled={busy}>{busy?"AGENDANDO...":"AGENDAR RODADA"}</button></div></form></main>;
}
