export default function PrivacyPage(){
  return <main className="legal-page"><article><a href="/">← Voltar</a><p className="eyebrow">DOCUMENTO PÚBLICO · VERSÃO TÉCNICA 2026-08-24</p><h1>Política de Privacidade</h1><p>Esta política descreve tecnicamente como o Conte os Feitos trata dados. A redação permanece sujeita à revisão humana e jurídica antes da abertura pública ou Google Play.</p>
  <h2>1. Produto e dados</h2><p>A plataforma oferece sete jogos bíblicos, Modo Livre, Desafios Diários e Eventos. Podemos tratar dados de conta e perfil, acessos, participações, respostas, resultados, XP, nível, moedas virtuais, inventário, equipamentos, missões, conquistas, notificações, aceites jurídicos e registros de segurança.</p>
  <h2>2. Finalidades e fundamentos</h2><p>Tratamos os dados necessários para fornecer a conta, autenticação, jogos, progresso, economia virtual e demais funcionalidades solicitadas pelo usuário. Quando aplicável, também consideramos obrigações legais ou regulatórias, exercício regular de direitos e legítimos interesses proporcionais de segurança, prevenção de abuso, auditoria e operação. Estes fundamentos e sua redação final ainda exigem revisão jurídica humana.</p>
  <h2>3. Visibilidade e isolamento</h2><p>Nome ou apelido pode aparecer conforme as configurações do perfil. Credenciais, contatos, dados administrativos e respostas protegidas não são públicos. Dados são isolados pela organização associada à sessão.</p>
  <h2>4. Conteúdo editorial</h2><p>Usuários autorizados podem criar ou revisar conteúdo no CMS. A autoria é registrada, mas o acervo editorial pertence à organização e não é apagado automaticamente com a conta do autor.</p>
  <h2>5. Segurança, operadores e transferências</h2><p>Usamos controles de acesso, senhas protegidas, sessões seguras, auditoria e backups. A Cloudflare é provedora crítica de hospedagem, Pages, Functions, Workers, D1 e observabilidade. O GitHub apoia desenvolvimento, integração contínua e artifacts operacionais e, por política, não deve receber o banco produtivo de usuários. Compartilhamentos via WhatsApp, quando oferecidos, são iniciados voluntariamente pelo usuário e ficam sujeitos às políticas desse serviço externo. Alguns provedores podem processar dados internacionalmente; os mecanismos contratuais e jurídicos aplicáveis ainda exigem verificação humana.</p>
  <h2>6. Exportação e exclusão</h2><p>O titular pode exportar dados estruturados pelo Perfil e solicitar exclusão ou anonimização. O atendimento exige verificação de identidade, encerra sessões e elimina ou anonimiza dados diretos quando aplicável. Registros mínimos podem ser preservados quando houver fundamento legítimo, e conteúdo organizacional pode ser mantido. Consulte as <a href="/privacidade/conta">instruções públicas para exclusão da conta</a>.</p>
  <h2>7. Retenção e backups</h2><p>Dados são conservados enquanto necessários às finalidades legítimas descritas. Não há exclusão automática por inatividade na v2. Backups podem conservar estado anterior até sua expiração operacional normal; após uma restauração, pedidos posteriores de exclusão ou anonimização devem ser reaplicados antes da reativação dos dados.</p>
  <h2>8. Controlador, direitos e contato</h2><p>O Conte os Feitos é atualmente controlado pela pessoa física responsável pelo projeto. Solicitações de consulta, correção, exportação, exclusão, privacidade ou suporte podem ser enviadas para <a href="mailto:suporteconteosfeitos@gmail.com">suporteconteosfeitos@gmail.com</a> ou iniciadas pelos controles da conta. CPF e endereço residencial não são publicados; a necessidade de endereço físico permanece sujeita à revisão jurídica.</p>
  <h2>9. Público com 18 anos ou mais</h2><p>O serviço é destinado exclusivamente a pessoas com 18 anos ou mais e não é destinado a crianças ou adolescentes. Não coletamos data de nascimento para essa finalidade; no cadastro, o usuário declara possuir pelo menos 18 anos.</p>
  <h2>10. Revisão necessária</h2><p><strong>REVISÃO HUMANA/JURÍDICA NECESSÁRIA ANTES DA ABERTURA PÚBLICA/GOOGLE PLAY.</strong></p><footer><a href="/termos">Ler Termos de Uso</a></footer></article></main>;
}
