import type { AppEnv } from "../../../../../_lib/auth";
import { requireAnyPermission, requirePermission } from "../../../../../_lib/permissions";
import { json } from "../../../../../_lib/security";
import { normalizeQuestion, validateQuestionResult } from "../../../../../_lib/questions";
async function owned(env:AppEnv,organizationId:string,questionId:string,revisionId:string){return env.DB.prepare(`SELECT qr.*,u.display_name AS authorName FROM question_revisions qr JOIN question_bank qb ON qb.id=qr.question_id JOIN users u ON u.id=qr.created_by WHERE qr.id=?1 AND qr.question_id=?2 AND qb.organization_id=?3`).bind(revisionId,questionId,organizationId).first()}
export const onRequestGet=async({request,env,params}:{request:Request;env:AppEnv;params:{id:string;revisionId:string}})=>{try{const user:any=await requireAnyPermission(request,env,["questions.edit","questions.review"]);const revision:any=await owned(env,user.organizationId,params.id,params.revisionId);if(!revision)return json({error:"not_found"},404);return json({revision:{...revision,snapshot:JSON.parse(revision.snapshot_json)}})}catch(response){if(response instanceof Response)return response;throw response}};
export const onRequestPost=async({request,env,params}:{request:Request;env:AppEnv;params:{id:string;revisionId:string}})=>{try{
 const user:any=await requirePermission(request,env,"questions.edit"),revision:any=await owned(env,user.organizationId,params.id,params.revisionId);if(!revision)return json({error:"not_found"},404);const current:any=await env.DB.prepare(`SELECT * FROM question_bank WHERE id=?1 AND organization_id=?2`).bind(params.id,user.organizationId).first(),currentChoices=await env.DB.prepare(`SELECT position,text,correct FROM question_bank_choices WHERE question_id=?1 ORDER BY position`).bind(params.id).all();if(!current)return json({error:"not_found"},404);
 let snapshot:any;try{snapshot=JSON.parse(revision.snapshot_json)}catch{return json({error:"invalid_snapshot"},409)}if(!Array.isArray(snapshot.choices)||snapshot.choices.filter((choice:any)=>Boolean(choice?.correct)).length!==1)return json({error:"invalid_snapshot",reason:"invalid_correct_choice"},409);const restored=validateQuestionResult({prompt:snapshot.prompt,choices:snapshot.choices.map((choice:any)=>choice?.text),correctIndex:snapshot.choices.findIndex((choice:any)=>Boolean(choice?.correct)),reference:snapshot.reference,book:snapshot.book,theme:snapshot.theme,category:snapshot.category,difficulty:snapshot.difficulty,commentary:snapshot.commentary});if(!restored.ok)return json({error:"invalid_snapshot",reason:restored.error},409);const duplicate=await env.DB.prepare("SELECT id FROM question_bank WHERE organization_id=?1 AND normalized_prompt=?2 AND id<>?3 AND status<>'archived'").bind(user.organizationId,normalizeQuestion(restored.value.prompt),params.id).first();if(duplicate)return json({error:"duplicate_question"},409);
 const now=Date.now(),version=Number(current.version||1),currentSnapshot=JSON.stringify({reference:current.reference,book:current.book,theme:current.theme,category:current.category,difficulty:current.difficulty,prompt:current.prompt,commentary:current.commentary,status:current.status,reviewStatus:current.review_status,choices:currentChoices.results});const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO question_revisions(id,question_id,version,snapshot_json,change_note,created_by,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7)`).bind(crypto.randomUUID(),params.id,version,currentSnapshot,`Antes de restaurar a versão ${revision.version}`,user.id,now),env.DB.prepare(`UPDATE question_bank SET reference=?1,book=?2,theme=?3,category=?4,difficulty=?5,prompt=?6,normalized_prompt=?7,commentary=?8,status='active',review_status='draft',version=?9,updated_by=?10,updated_at=?11 WHERE id=?12 AND organization_id=?13`).bind(restored.value.reference,restored.value.book,restored.value.theme,restored.value.category,restored.value.difficulty,restored.value.prompt,normalizeQuestion(restored.value.prompt),restored.value.commentary,version+1,user.id,now,params.id,user.organizationId),env.DB.prepare(`DELETE FROM question_bank_choices WHERE question_id=?1`).bind(params.id)];restored.value.choices.forEach((choice,position)=>statements.push(env.DB.prepare(`INSERT INTO question_bank_choices(id,question_id,position,text,correct) VALUES(?1,?2,?3,?4,?5)`).bind(crypto.randomUUID(),params.id,position,choice,position===restored.value.correctIndex?1:0)));statements.push(env.DB.prepare(`INSERT INTO audit_logs(id,organization_id,actor_user_id,action,entity_type,entity_id,details_json,created_at) VALUES(?1,?2,?3,'question.revision_restored','question_bank',?4,?5,?6)`).bind(crypto.randomUUID(),user.organizationId,user.id,params.id,JSON.stringify({restoredVersion:revision.version,newVersion:version+1}),now));await env.DB.batch(statements);return json({ok:true,version:version+1,reviewStatus:"draft"});
}catch(response){if(response instanceof Response)return response;throw response}};
