import type { AppEnv } from "../../_lib/auth";
import { requirePermission } from "../../_lib/permissions";
import { json } from "../../_lib/security";

export const onRequestGet = async ({ request, env }: { request: Request; env: AppEnv }) => {
  try {
    const user: any = await requirePermission(request, env, "reports.view");
    const days = Math.max(7, Math.min(365, Number(new URL(request.url).searchParams.get("days")) || 90));
    const since = Date.now() - days * 86_400_000;
    const org = user.organizationId;
    const eligible = "r.status<>'cancelled' AND a.mode='official' AND a.status='completed'";
    const summary = await env.DB.prepare(`WITH completed AS (SELECT a.*,(SELECT COUNT(*) FROM questions q WHERE q.round_id=a.round_id) questionCount FROM attempts a JOIN users u ON u.id=a.user_id JOIN rounds r ON r.id=a.round_id WHERE u.organization_id=?1 AND ${eligible} AND a.completed_at>=?2) SELECT COUNT(DISTINCT user_id) participants,COUNT(*) attempts,COUNT(DISTINCT round_id) rounds,COALESCE(ROUND(AVG(score)),0) averageScore,COALESCE(ROUND(AVG(correct_answers*100.0/NULLIF(questionCount,0))),0) averageAccuracy FROM completed`).bind(org,since).first();
    const participation = await env.DB.prepare(`WITH completed AS (SELECT a.*,(SELECT COUNT(*) FROM questions q WHERE q.round_id=a.round_id) questionCount FROM attempts a WHERE a.mode='official' AND a.status='completed') SELECT r.id,r.title,r.theme,r.opens_at opensAt,r.round_type roundType,COUNT(DISTINCT completed.user_id) participants,COUNT(completed.id) attempts,COALESCE(ROUND(AVG(completed.score)),0) averageScore,COALESCE(ROUND(AVG(completed.correct_answers*100.0/NULLIF(completed.questionCount,0))),0) accuracy FROM rounds r LEFT JOIN completed ON completed.round_id=r.id WHERE r.organization_id=?1 AND r.status<>'cancelled' AND r.opens_at>=?2 GROUP BY r.id ORDER BY r.opens_at DESC LIMIT 20`).bind(org,since).all();
    const trend = await env.DB.prepare(`SELECT strftime('%Y-%W',a.completed_at/1000,'unixepoch') week,COUNT(DISTINCT a.user_id) participants,COUNT(a.id) attempts,ROUND(AVG(a.score)) averageScore,ROUND(AVG(a.correct_answers),1) averageCorrect FROM attempts a JOIN users u ON u.id=a.user_id JOIN rounds r ON r.id=a.round_id WHERE u.organization_id=?1 AND ${eligible} AND a.completed_at>=?2 GROUP BY week ORDER BY week`).bind(org,since).all();
    const dimensions = await env.DB.prepare(`SELECT COALESCE(qb.theme,r.theme,'Sem tema') theme,COALESCE(qb.book,'Não informado') book,COALESCE(qb.difficulty,'medium') difficulty,COUNT(*) answers,SUM(aa.correct) correct,ROUND(SUM(aa.correct)*100.0/COUNT(*)) accuracy FROM attempt_answers aa JOIN attempts a ON a.id=aa.attempt_id JOIN users u ON u.id=a.user_id JOIN rounds r ON r.id=a.round_id JOIN questions q ON q.id=aa.question_id LEFT JOIN question_bank qb ON qb.id=q.source_question_id WHERE u.organization_id=?1 AND ${eligible} AND a.completed_at>=?2 GROUP BY theme,book,difficulty ORDER BY answers DESC`).bind(org,since).all();
    const hardest = await env.DB.prepare(`SELECT q.id,q.prompt,q.reference,COALESCE(qb.theme,r.theme) theme,COUNT(*) answers,SUM(aa.correct) correct,ROUND(SUM(aa.correct)*100.0/COUNT(*)) accuracy,ROUND(AVG(aa.response_time_ms)) averageTimeMs FROM attempt_answers aa JOIN attempts a ON a.id=aa.attempt_id JOIN users u ON u.id=a.user_id JOIN rounds r ON r.id=a.round_id JOIN questions q ON q.id=aa.question_id LEFT JOIN question_bank qb ON qb.id=q.source_question_id WHERE u.organization_id=?1 AND ${eligible} AND a.completed_at>=?2 GROUP BY q.id HAVING COUNT(*)>=2 ORDER BY accuracy ASC,answers DESC LIMIT 15`).bind(org,since).all();
    return json({days,summary,participation:participation.results,trend:trend.results,dimensions:dimensions.results,hardest:hardest.results});
  } catch (response) { if (response instanceof Response) return response; throw response; }
};
