import { requirePermission } from "../../_lib/permissions";
import type { AppEnv } from "../../_lib/auth";
import { json } from "../../_lib/security";
import { QUESTION_COUNT } from "../../_lib/questions";

const required=["organizations","groups","users","invitations","sessions","rounds","questions","choices","attempts","attempt_answers","audit_logs","question_bank","question_bank_choices","user_permissions","question_revisions","seasons","user_review_progress","announcements","account_recovery_codes","privacy_requests","ai_question_suggestions","batch_operations","season_snapshots","season_awards","legal_consents","abuse_counters"];
const expected:Record<string,string[]>={sessions:["user_agent","ip_hash"],attempts:["resumed_count","last_resumed_at","question_order_json"],users:["nickname","bio","favorite_book","favorite_verse"],rounds:["season_id","round_type","advanced_rules_json"],seasons:["closed_at","snapshot_created_at"],choices:["position"],legal_consents:["organization_id","document_type","ip_hash","user_agent"]};

export const onRequestGet=async({request,env}:{request:Request;env:AppEnv})=>{try{
 const user:any=await requirePermission(request,env,"reports.view"),now=Date.now(),tables=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table'").all(),found=new Set((tables.results as any[]).map(row=>row.name)),missing=required.filter(name=>!found.has(name)),checks:any[]=[];
 for(const[name,sql]of[["users","SELECT COUNT(*) total FROM users WHERE organization_id=?1"],["rounds","SELECT COUNT(*) total FROM rounds WHERE organization_id=?1"],["questions","SELECT COUNT(*) total FROM question_bank WHERE organization_id=?1"],["attempts","SELECT COUNT(*) total FROM attempts a JOIN users u ON u.id=a.user_id WHERE u.organization_id=?1"],["staleAttempts","SELECT COUNT(*) total FROM attempts a JOIN users u ON u.id=a.user_id WHERE u.organization_id=?1 AND a.status='in_progress' AND a.started_at<?2"]]as const){try{const row:any=name==="staleAttempts"?await env.DB.prepare(sql).bind(user.organizationId,now-86400000).first():await env.DB.prepare(sql).bind(user.organizationId).first();checks.push({name,ok:true,total:Number(row?.total||0)})}catch{checks.push({name,ok:false})}}
 const overlaps=await env.DB.prepare("SELECT a.id firstId,a.title firstTitle,b.id secondId,b.title secondTitle FROM rounds a JOIN rounds b ON a.organization_id=b.organization_id AND a.id<b.id AND a.opens_at<b.closes_at AND a.closes_at>b.opens_at WHERE a.organization_id=?1 AND a.status IN ('scheduled','active') AND b.status IN ('scheduled','active') ORDER BY a.opens_at LIMIT 50").bind(user.organizationId).all();
 const invalidRounds=await env.DB.prepare("SELECT r.id,r.title,r.status,r.round_type roundType,r.season_id seasonId,r.opens_at opensAt,r.closes_at closesAt,(SELECT COUNT(*) FROM questions q WHERE q.round_id=r.id AND q.active=1) questionCount FROM rounds r WHERE r.organization_id=?1 AND ((r.opens_at>=r.closes_at) OR (r.round_type='regular' AND r.season_id IS NULL) OR (r.status IN ('scheduled','active') AND (SELECT COUNT(*) FROM questions q WHERE q.round_id=r.id AND q.active=1)<>?2)) ORDER BY r.opens_at LIMIT 100").bind(user.organizationId,QUESTION_COUNT).all();
 checks.push({name:"roundOverlaps",ok:overlaps.results.length===0,total:overlaps.results.length,items:overlaps.results},{name:"invalidRounds",ok:invalidRounds.results.length===0,total:invalidRounds.results.length,items:invalidRounds.results},{name:"aiConfiguration",ok:Boolean(env.AI),total:env.AI?1:0,configured:Boolean(env.AI)},{name:"serviceWorker",ok:true,total:5,expectedVersion:"conte-os-feitos-v5"});
 const missingColumns:string[]=[];for(const[table,names]of Object.entries(expected)){if(!found.has(table))continue;const columns=new Set(((await env.DB.prepare(`PRAGMA table_info(${table})`).all()).results as any[]).map(row=>row.name));for(const name of names)if(!columns.has(name))missingColumns.push(`${table}.${name}`)}
 const requiredIndexes=["choices_question_position_uq","attempt_answers_order_uq","attempts_user_round_mode_number_uq","rounds_window_idx"],indexes=new Set(((await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='index'").all()).results as any[]).map(row=>row.name)),missingIndexes=requiredIndexes.filter(name=>!indexes.has(name));
 const status=missing.length||missingColumns.length||missingIndexes.length||checks.some(check=>!check.ok)?"attention":"healthy",recommendations:string[]=[];if(missing.length||missingColumns.length||missingIndexes.length)recommendations.push("Execute as migrations D1 pendentes antes de publicar.");if(checks.find(check=>check.name==="staleAttempts"&&check.total>0))recommendations.push("Existem tentativas em andamento há mais de 24 horas; revise antes do lançamento.");if(overlaps.results.length)recommendations.push("Existem rodadas sobrepostas. Encerre ou reagende os registros listados; nenhum dado foi alterado automaticamente.");if(invalidRounds.results.length)recommendations.push("Existem rodadas com período, temporada ou quantidade de perguntas inconsistente.");if(!env.AI)recommendations.push("O binding Workers AI chamado AI não está configurado.");
 return json({status,checkedAt:now,schemaTarget:"0018_competitive_integrity",tables:{required:required.length,found:required.length-missing.length,missing},missingColumns,missingIndexes,checks,recommendations,roundConflicts:{count:overlaps.results.length,items:overlaps.results},invalidRounds:{count:invalidRounds.results.length,items:invalidRounds.results},ai:{configured:Boolean(env.AI)},serviceWorker:{expectedVersion:"conte-os-feitos-v5"}});
}catch(response){if(response instanceof Response)return response;throw response}};
