import {requireAdmin,type AppEnv} from "../../_lib/auth";
import {json}from"../../_lib/security";
import {validateQuestionResult}from"../../_lib/questions";
import {validateStoredRound}from"../../_lib/rounds";

const Q=[
 ["João 9","Qual era a condição do homem em João 9 antes de encontrar Jesus?",["Era paralítico desde o nascimento","Era leproso","Era cego de nascença","Era surdo"],2,"Jesus mostrou que aquela situação serviria para manifestar a glória de Deus."],
 ["Atos 3","Quem disse: Não tenho prata nem ouro, mas o que tenho isso te dou?",["Paulo","João Batista","Pedro","Filipe"],2,"Pedro falou isso ao coxo da Porta Formosa antes de sua cura."],
 ["João 9","Após ser curado por Jesus, o homem cego de João 9 fez o quê?",["Voltou imediatamente para casa","Escondeu o milagre","Pediu dinheiro","Contou o que Jesus havia feito, mesmo sendo questionado pelos fariseus"],3,"Ele não teve vergonha de testemunhar."],
 ["Salmos 105:1","Segundo Salmos 105:1, devemos tornar conhecidos entre as nações...",["nossos sonhos","nossas dificuldades","nossas vitórias","os feitos do Senhor"],3,"Deem graças ao Senhor e tornem conhecidos entre as nações os seus feitos."],
 ["Lucas 17","Qual destes personagens voltou para agradecer Jesus depois de ser curado?",["O paralítico de Cafarnaum","Bartimeu","Um dos dez leprosos","O cego de Betsaida"],2,"Somente um voltou para agradecer, e era samaritano."],
 ["João 9","Quando perguntaram por que o homem havia nascido cego, Jesus respondeu que isso aconteceu para...",["Castigar seus pais","Mostrar consequência do pecado","Manifestar as obras de Deus","Provar a fé dos discípulos"],2,"Jesus explicou que as obras de Deus seriam manifestadas na vida daquele homem."],
 ["Atos 3","Qual foi a primeira reação do homem curado na Porta Formosa?",["Foi para casa","Dormiu","Começou a pregar imediatamente","Entrou no templo andando, saltando e louvando a Deus"],3,"Todos o viram andando e louvando a Deus."],
 ["Milagres","Qual destes NÃO foi um milagre realizado por Jesus?",["Transformar água em vinho","Ressuscitar Lázaro","Curar um cego de nascença","Abrir o Mar Vermelho"],3,"Quem abriu o Mar Vermelho foi Deus através de Moisés."],
 ["Salmos 105:1","Complete: Deem graças ao Senhor, invoquem o seu nome; tornem conhecidos entre as nações...",["a sua Palavra","os seus mandamentos","os seus feitos","a sua justiça"],2,"O salmista nos convida a contar entre as nações os feitos do Senhor."],
 ["Testemunho","Qual é o principal objetivo de compartilhar um testemunho?",["Mostrar como somos fortes","Impressionar as pessoas","Ser reconhecido pela igreja","Glorificar a Deus e fortalecer a fé de outras pessoas"],3,"Nosso testemunho aponta para o que Deus fez e encoraja outras pessoas a crer."]
] as const;

export const onRequestPost=async({request,env}:{request:Request;env:AppEnv})=>{try{const admin:any=await requireAdmin(request,env);if(await env.DB.prepare("SELECT id FROM rounds WHERE organization_id=?1 AND title LIKE 'Rodada 1%'").bind(admin.organizationId).first())return json({error:"already_exists"},409);const validated=Q.map(item=>validateQuestionResult({reference:item[0],prompt:item[1],choices:[...item[2]],correctIndex:item[3],theme:"Testemunhos, milagres e os feitos de Deus",difficulty:"medium",commentary:item[4]}));const invalid=validated.find(item=>!item.ok);if(invalid&&!invalid.ok)return json({error:"invalid_seed",reason:invalid.error},409);const now=Date.now(),date=new Date(now);let add=(7-date.getUTCDay())%7;if(add===0)add=7;const closes=Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()+add,12,30),roundId=crypto.randomUUID(),statements:D1PreparedStatement[]=[env.DB.prepare("INSERT INTO rounds(id,organization_id,title,theme,description,status,opens_at,closes_at,official_attempt_limit,seconds_per_question,created_by,created_at,updated_at) VALUES(?1,?2,'Rodada 1 — Contem o que Deus fez','Testemunhos, milagres e os feitos de Deus','Conte o que Deus fez e fortaleça sua fé.','draft',?3,?4,3,20,?5,?3,?3)").bind(roundId,admin.organizationId,now,closes,admin.id)];for(const[item,index]of Q.entries()){const questionId=crypto.randomUUID();statements.push(env.DB.prepare("INSERT INTO questions(id,round_id,position,reference,prompt,commentary,active) VALUES(?1,?2,?3,?4,?5,?6,1)").bind(questionId,roundId,index+1,item[0],item[1],item[4]));item[2].forEach((choice,position)=>statements.push(env.DB.prepare("INSERT INTO choices(id,question_id,text,position,correct) VALUES(?1,?2,?3,?4,?5)").bind(crypto.randomUUID(),questionId,choice,position,position===item[3]?1:0)))}await env.DB.batch(statements);const integrity=await validateStoredRound(env,roundId,admin.organizationId);if(!integrity.ok)return json({error:"round_not_publishable",reason:integrity.error,roundId},409);await env.DB.batch([env.DB.prepare("UPDATE rounds SET status='active',updated_at=?1 WHERE id=?2 AND organization_id=?3 AND status='draft'").bind(Date.now(),roundId,admin.organizationId),env.DB.prepare("INSERT INTO audit_logs(id,organization_id,actor_user_id,action,entity_type,entity_id,details_json,created_at) VALUES(?1,?2,?3,'round.seeded_and_published','round',?4,?5,?6)").bind(crypto.randomUUID(),admin.organizationId,admin.id,roundId,JSON.stringify({questionCount:Q.length}),Date.now())]);return json({ok:true,roundId,closesAt:closes},201)}catch(response){if(response instanceof Response)return response;throw response}};
