import {requireAdmin,type AppEnv} from "../../_lib/auth";import{json}from"../../_lib/security";
const Q:any[]=[
["João 9","Qual era a condição do homem em João 9 antes de encontrar Jesus?",["Era paralítico desde o nascimento","Era leproso","Era cego de nascença","Era surdo"],2,"Jesus mostrou que aquela situação serviria para manifestar a glória de Deus."],
["Atos 3","Quem disse: Não tenho prata nem ouro, mas o que tenho isso te dou?",["Paulo","João Batista","Pedro","Filipe"],2,"Pedro falou isso ao coxo da Porta Formosa antes de sua cura."],
["João 9","Após ser curado por Jesus, o homem cego de João 9 fez o quê?",["Voltou imediatamente para casa","Escondeu o milagre","Pediu dinheiro","Contou o que Jesus havia feito, mesmo sendo questionado pelos fariseus"],3,"Ele não teve vergonha de testemunhar."],
["Salmos 105:1","Segundo Salmos 105:1, devemos tornar conhecidos entre as nações...",["nossos sonhos","nossas dificuldades","nossas vitórias","os feitos do Senhor"],3,"Deem graças ao Senhor e tornem conhecidos entre as nações os seus feitos."],
["Lucas 17","Qual destes personagens voltou para agradecer Jesus depois de ser curado?",["O paralítico de Cafarnaum","Bartimeu","Um dos dez leprosos","O cego de Betsaida"],2,"Somente um voltou para agradecer, e era samaritano."],
["João 9","Quando perguntaram por que o homem havia nascido cego, Jesus respondeu que isso aconteceu para...",["Castigar seus pais","Mostrar consequência do pecado","Manifestar as obras de Deus","Provar a fé dos discípulos"],2,"Jesus explicou que as obras de Deus seriam manifestadas na vida daquele homem."],
["Atos 3","Qual foi a primeira reação do homem curado na Porta Formosa?",["Foi para casa","Dormiu","Começou a pregar imediatamente","Entrou no templo andando, saltando e louvando a Deus"],3,"Todos o viram andando e louvando a Deus."],
["Milagres","Qual destes NÃO foi um milagre realizado por Jesus?",["Transformar água em vinho","Ressuscitar Lázaro","Curar um cego de nascença","Abrir o Mar Vermelho"],3,"Quem abriu o Mar Vermelho foi Deus através de Moisés."],
["Salmos 105:1","Complete: Deem graças ao Senhor, invoquem o seu nome; tornem conhecidos entre as nações...",["a sua Palavra","os seus mandamentos","os seus feitos","a sua justiça"],2,"O salmista nos convida a contar entre as nações os feitos do Senhor."],
["Testemunho","Qual é o principal objetivo de compartilhar um testemunho?",["Mostrar como somos fortes","Impressionar as pessoas","Ser reconhecido pela igreja","Glorificar a Deus e fortalecer a fé de outras pessoas"],3,"Nosso testemunho aponta para o que Deus fez e encoraja outras pessoas a crer."]];
export const onRequestPost=async({request,env}:{request:Request;env:AppEnv})=>{try{const admin:any=await requireAdmin(request,env);if(await env.DB.prepare("SELECT id FROM rounds WHERE organization_id=?1 AND title LIKE 'Rodada 1%'").bind(admin.organizationId).first())return json({error:'already_exists'},409);const now=Date.now(),d=new Date(now);let add=(7-d.getUTCDay())%7;if(add===0)add=7;const closes=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()+add,12,30),rid=crypto.randomUUID();const s=[env.DB.prepare("INSERT INTO rounds (id,organization_id,title,theme,description,status,opens_at,closes_at,official_attempt_limit,seconds_per_question,created_by,created_at,updated_at) VALUES (?1,?2,'Rodada 1 — Contem o que Deus fez','Testemunhos, milagres e os feitos de Deus','Conte o que Deus fez e fortaleça sua fé.','active',?3,?4,3,20,?5,?3,?3)").bind(rid,admin.organizationId,now,closes,admin.id)];Q.forEach((q,i)=>{const qid=crypto.randomUUID();s.push(env.DB.prepare("INSERT INTO questions (id,round_id,position,reference,prompt,commentary,active) VALUES (?1,?2,?3,?4,?5,?6,1)").bind(qid,rid,i+1,q[0],q[1],q[4]));q[2].forEach((c:string,j:number)=>s.push(env.DB.prepare("INSERT INTO choices (id,question_id,text,correct) VALUES (?1,?2,?3,?4)").bind(crypto.randomUUID(),qid,c,j===q[3]?1:0)))});await env.DB.batch(s);return json({ok:true,roundId:rid,closesAt:closes},201)}catch(response){if(response instanceof Response)return response;throw response;}};
